/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;

import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author lordz
 */
public class ClassForm extends javax.swing.JFrame {

    /**
     * Creates new form ClassForm
     */
    public ClassForm(String val) {
        initComponents();
        
        adminName.setText(val);
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
        }      
     
        getTeachers();
        //Setting the icon    
        java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
          
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    public static Connection conn;
     DefaultListModel<String> secListModel = new DefaultListModel<>();
    public static DefaultComboBoxModel<String> secModel = new DefaultComboBoxModel<>();
    public static DefaultComboBoxModel<String> subModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> tcModel = new DefaultComboBoxModel<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        adviserName = new javax.swing.JComboBox<>();
        strandSlctn = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        studNum = new javax.swing.JLabel();
        studSize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        availableSec = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        customSec = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        adminName = new javax.swing.JLabel();
        adminTitle1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Choose Strand:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 220, 118, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Assign Adviser:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 360, 130, 21);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setText("Available Sections");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(680, 230, 252, 27);

        adviserName.setModel(tcModel);
        getContentPane().add(adviserName);
        adviserName.setBounds(500, 350, 130, 33);

        strandSlctn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","ABM", "GAS", "HE", "ICT" }));
        strandSlctn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandSlctnActionPerformed(evt);
            }
        });
        strandSlctn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                strandSlctnKeyPressed(evt);
            }
        });
        getContentPane().add(strandSlctn);
        strandSlctn.setBounds(500, 220, 126, 33);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 470, 120, 40);

        studNum.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        studNum.setText("There are x students in this strand.");
        getContentPane().add(studNum);
        studNum.setBounds(680, 210, 260, 16);

        studSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studSizeActionPerformed(evt);
            }
        });
        studSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                studSizeKeyTyped(evt);
            }
        });
        getContentPane().add(studSize);
        studSize.setBounds(500, 280, 130, 37);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setText("Assign No. of Students: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 290, 190, 21);

        availableSec.setModel(secListModel);
        jScrollPane1.setViewportView(availableSec);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(680, 270, 290, 170);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 51));
        jLabel8.setText("CLASS MANAGEMENT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 130, 460, 70);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 560, 130, 50);

        customSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customSecActionPerformed(evt);
            }
        });
        getContentPane().add(customSec);
        customSec.setBounds(680, 472, 170, 40);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 480, 80, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setText("Add a new Section");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 450, 120, 14);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("LOG OUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1100, 50, 110, 40);

        adminName.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminName.setText("Admin!");
        getContentPane().add(adminName);
        adminName.setBounds(250, 50, 150, 20);

        adminTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle1.setText("Welcome, ");
        getContentPane().add(adminTitle1);
        adminTitle1.setBounds(160, 50, 90, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(1280, 800));
        jLabel5.setMinimumSize(new java.awt.Dimension(1280, 800));
        jLabel5.setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1296, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studSizeActionPerformed

    private void strandSlctnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandSlctnActionPerformed
        String strandVal = (String) strandSlctn.getSelectedItem();
        String getTotalStud = "SELECT COUNT(STRAND) AS studCount FROM sf1_db WHERE STRAND = ?";
        sectionMgmt();
        
        
        
        if(strandVal.equals("ICT")){
            try {
                PreparedStatement ict = conn.prepareStatement(getTotalStud);
                ict.setString(1, strandVal);
                ResultSet findTotal = ict.executeQuery();
                    if(findTotal.next()){
                        int count = findTotal.getInt("studCount");
                        studNum.setText("There are "+count+" student/s in this strand.");
                    }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(strandVal.equals("HE")){
            try {
                PreparedStatement he = conn.prepareStatement(getTotalStud);
                he.setString(1, strandVal);
                ResultSet findTotal = he.executeQuery();
                    if(findTotal.next()){
                        int count = findTotal.getInt("studCount");
                        studNum.setText("There are "+count+" student/s in this strand.");
                    }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(strandVal.equals("ABM")){
            try {
                PreparedStatement abm = conn.prepareStatement(getTotalStud);
                abm.setString(1, strandVal);
                ResultSet findTotal = abm.executeQuery();
                    if(findTotal.next()){
                        int count = findTotal.getInt("studCount");
                        studNum.setText("There are "+count+" student/s in this strand.");
                    }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(strandVal.equals("GAS")){
            try {
                PreparedStatement gas = conn.prepareStatement(getTotalStud);
                gas.setString(1, strandVal);
                ResultSet findTotal = gas.executeQuery();
                    if(findTotal.next()){
                        int count = findTotal.getInt("studCount");
                        studNum.setText("There are "+count+" student/s in this strand.");
                    }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Select a strand.");
        }
    }//GEN-LAST:event_strandSlctnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to submit?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(response == JOptionPane.YES_OPTION){  
        String strandDD = (String) strandSlctn.getSelectedItem();
            String classSize = studSize.getText();
            String adviser = (String) adviserName.getSelectedItem();
            String secName = (String) availableSec.getSelectedValue();
        if(strandDD.equals("")){
            JOptionPane.showMessageDialog(null, "Please select a Specialization.");
        }else if(classSize.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter a class size.");
        }else if(adviser.equals("")){
            JOptionPane.showMessageDialog(null, "Please select an Adviser.");
        }else{
            try {
                String sqlQuery = "INSERT INTO classlist(Class_Name, Class_Size,Adviser_Name,STRAND) VALUES(?,?,?,?)";
                    PreparedStatement insertClass = conn.prepareStatement(sqlQuery);
                        insertClass.setString(1, secName);
                        insertClass.setString(2, classSize);
                        insertClass.setString(3, adviser);
                        insertClass.setString(4, strandDD);
                            insertClass.executeUpdate();
                            
                         addToDB();
                JOptionPane.showMessageDialog(null,"New class created!");       
                  
                
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error adding class:  " + ex.getMessage());
            }
            
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String adminName = this.adminName.getText();
        
        ClassAdd ca = new ClassAdd(this.adminName.getText());
        ca.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void studSizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studSizeKeyTyped
           char c = evt.getKeyChar();
      if(!Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_studSizeKeyTyped

    private void customSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customSecActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String scName = (String) strandSlctn.getSelectedItem();
        String newSec = customSec.getText();
        if(scName.equals("")){
            JOptionPane.showMessageDialog(null, "Please select a strand first");
        }else{
            secListModel.addElement(newSec);    
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         int closeApp = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
                    if(closeApp == JOptionPane.YES_OPTION) {
                            dispose();
                        } 
    }//GEN-LAST:event_formWindowClosing

    private void strandSlctnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strandSlctnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        studSize.requestFocusInWindow();  
     }
    }//GEN-LAST:event_strandSlctnKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            dispose();
            l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public void getTeachers() {
    String getTC = "SELECT FullName, username FROM tblaccounts";
    try {
        PreparedStatement applySQL = conn.prepareStatement(getTC);
        ResultSet tcVal = applySQL.executeQuery();
        
        System.out.println("All Rows:");
        while(tcVal.next()) {
            String getUN = tcVal.getString("username");
            String tcName = tcVal.getString("FullName");
            System.out.println("Username: " + getUN + ", FullName: " + tcName);
        }
        
        
        tcVal = applySQL.executeQuery();
        
        System.out.println("\nRows with 'TCH' in username:");
        while(tcVal.next()) {
            String getUN = tcVal.getString("username");
            if(getUN.contains("TCH")) {
                String tcName = tcVal.getString("FullName");
                tcModel.addElement(tcName);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    public void addToDB(){
        String newSection = (String) availableSec.getSelectedValue();
        String strand = (String) strandSlctn.getSelectedItem();
            if(strand.equals("ICT")){
            try {
                PreparedStatement addVal = conn.prepareStatement("INSERT INTO ictsections(SctnName) VALUES(?)");
                    addVal.setString(1,newSection);
                addVal.executeUpdate();
                
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
    }
    
    public void sectionMgmt(){
     String chooseStrand =(String) strandSlctn.getSelectedItem();
            secListModel.clear();
     
        if(chooseStrand.equals("ICT")){
            try {
                String ictStrand = "SELECT SctnName FROM ictsections";
                PreparedStatement getICT = conn.prepareStatement(ictStrand);
                ResultSet getSection = getICT.executeQuery();
                
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("HE")){
            try {
                String heStrand = "SELECT SctnName FROM hesections";
                PreparedStatement getHE = conn.prepareStatement(heStrand);
                ResultSet getSection = getHE.executeQuery();
                
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("ABM")){
                        try {
                String abmStrand = "SELECT SctnName FROM ABMsections";
                PreparedStatement getABM = conn.prepareStatement(abmStrand);
                ResultSet getSection = getABM.executeQuery();
                
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("GAS")){
                        try {
                String gasStrand = "SELECT SctnName FROM gassections";
                PreparedStatement getGAS = conn.prepareStatement(gasStrand);
                ResultSet getSection = getGAS.executeQuery();
                
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            
        }
    } 
    
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void launch(String admName) {
        ClassForm tl = new ClassForm(admName);
         
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        
        
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(ClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(ClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(ClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(ClassForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    launch("");
                }
            });
        
        
        
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminName;
    public javax.swing.JLabel adminTitle1;
    private javax.swing.JComboBox<String> adviserName;
    private javax.swing.JList<String> availableSec;
    private javax.swing.JTextField customSec;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> strandSlctn;
    private javax.swing.JLabel studNum;
    private javax.swing.JTextField studSize;
    // End of variables declaration//GEN-END:variables
}
