/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aicel
 */
public class ITADDACCFORM extends javax.swing.JFrame {

    /**
     * Creates new form ITADDACCFORM
     */
    public ITADDACCFORM(String val) {
        initComponents();
        ITName.setText(val);
        
        try {
            connectDB();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ITADDACCFORM.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ITADDACCFORM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        fName.setEnabled(false);
        lName.setEnabled(false);
        tchName.setEnabled(false);
        
        
        tchName.addItem("Select a Teacher: ");
        getTeachers();
        getItem();
    }

Connection conn;
DefaultComboBoxModel<String> tcModel = new DefaultComboBoxModel<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        passbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        button = new javax.swing.JButton();
        USERNAME = new javax.swing.JComboBox<>();
        userVal = new javax.swing.JLabel();
        lName = new javax.swing.JTextField();
        fName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tchName = new javax.swing.JComboBox<>();
        uName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        accTable = new javax.swing.JTable();
        ITName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namefield = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("LAST NAME:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(330, 380, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("PASSWORD:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 580, 140, 16);

        passbox.setBackground(new java.awt.Color(204, 204, 204));
        passbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passboxActionPerformed(evt);
            }
        });
        getContentPane().add(passbox);
        passbox.setBounds(60, 610, 490, 40);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 50, 110, 40);

        button.setBackground(new java.awt.Color(204, 255, 204));
        button.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        button.setForeground(new java.awt.Color(51, 51, 51));
        button.setText("SUBMIT");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button);
        button.setBounds(240, 680, 110, 40);

        USERNAME.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select account type: ","IT", "HR", "Admin", "Teacher" }));
        USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAMEActionPerformed(evt);
            }
        });
        getContentPane().add(USERNAME);
        USERNAME.setBounds(50, 320, 250, 40);

        userVal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        userVal.setText("ACTYPE_");
        getContentPane().add(userVal);
        userVal.setBounds(70, 520, 120, 40);

        lName.setBackground(new java.awt.Color(204, 204, 204));
        lName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameActionPerformed(evt);
            }
        });
        lName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lNameKeyTyped(evt);
            }
        });
        getContentPane().add(lName);
        lName.setBounds(330, 410, 220, 40);

        fName.setBackground(new java.awt.Color(204, 204, 204));
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        fName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameKeyTyped(evt);
            }
        });
        getContentPane().add(fName);
        fName.setBounds(50, 410, 250, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("FOR TEACHER ACCOUNT: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 290, 220, 22);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 68, 45));
        jLabel4.setText("ADD ACCOUNT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 230, 270, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("USERNAME:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 480, 140, 22);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText(" FIRST NAME:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 380, 110, 22);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("SELECT ACCOUNT TYPE: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 290, 220, 22);

        tchName.setModel(tcModel);
        tchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tchNameActionPerformed(evt);
            }
        });
        getContentPane().add(tchName);
        tchName.setBounds(330, 320, 220, 40);

        uName.setBackground(new java.awt.Color(204, 204, 204));
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });
        uName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uNameKeyTyped(evt);
            }
        });
        getContentPane().add(uName);
        uName.setBounds(210, 520, 250, 40);

        accTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "username", "User Type"
            }
        ));
        jScrollPane1.setViewportView(accTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(600, 250, 660, 380);

        ITName.setText("ITName");
        getContentPane().add(ITName);
        ITName.setBounds(210, 60, 180, 16);

        jLabel9.setText("Welcome,");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 60, 60, 16);

        namefield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        getContentPane().add(namefield);
        namefield.setBounds(0, 0, 1330, 800);

        setSize(new java.awt.Dimension(1294, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passboxActionPerformed
       
    }//GEN-LAST:event_passboxActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        if(!userVal.getText().equals("TCH_")){
            if(fName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a first name");
            
            }else if(lName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a last name");
            }else if(uName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a username");
        }else if(passbox.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a password");
            }else{
                insertAcc();
            }
            
        }else if(uName.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a username");
        }else if(passbox.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Please put a password");
            }else{
                insertAcc();
            }
       
    getItem(); 
 
    }//GEN-LAST:event_buttonActionPerformed

    
     public void getItem(){
         
             try {    
                 PreparedStatement getSec = conn.prepareStatement("SELECT FullName, username, userType FROM tblaccounts ");
                    
                    ResultSet findSection = getSec.executeQuery();
                         ResultSetMetaData getColVal = (ResultSetMetaData) findSection.getMetaData();
            int q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) accTable.getModel();
            secAssign.setRowCount(0);
            accTable.setDefaultEditor(Object.class, null);
            while (findSection.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = findSection.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
             } catch (SQLException ex) {
                 Logger.getLogger(tablesf1.class.getName()).log(Level.SEVERE, null, ex);
             }
         
               
    }
    
    
    
    public void insertAcc(){
        String firstName = fName.getText();
            char FirstInitial = firstName.charAt(0);
            String lastName = lName.getText();
            String accountType = (String) USERNAME.getSelectedItem();
            String pass = passbox.getText();
            String uType =(String) USERNAME.getSelectedItem();
            
            
            String fullUsername = userVal.getText() + uName.getText();//IT_JLLONA
            String fullName = firstName+"\n"+lastName;
            
             // Check for special characters
        boolean hasSpecialChar = Pattern.compile("[!@#$%^&*(),.?\":{}|<>]").matcher(pass).find();
        // Check for at least one number
        boolean hasNumber = Pattern.compile("[0-9]").matcher(pass).find();
        // Check for at least one uppercase letter
        boolean hasUpperCase = Pattern.compile("[A-Z]").matcher(pass).find();
                
            if(pass.length() < 8 || hasSpecialChar == false || hasNumber == false || hasUpperCase == false){
                JOptionPane.showMessageDialog(null,"Please follow the format");
           
            }else{
            try {
                PreparedStatement insertAcc = conn.prepareStatement("INSERT INTO tblaccounts(FullName, username, password,userType) VALUES(?,?,?,?)");
                insertAcc.setString(1,fullName);
                insertAcc.setString(2,fullUsername);
                insertAcc.setString(3,pass);
                insertAcc.setString(4,uType);
                insertAcc.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"You have created a new account: " +fullUsername);
            } catch (SQLException ex) {
                Logger.getLogger(ITADDACCFORM.class.getName()).log(Level.SEVERE, null, ex);
            }
            }   
    }
    
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
        dispose();
        l1.setVisible(true);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAMEActionPerformed
         String cbVal = (String) USERNAME.getSelectedItem();
        
         fName.setText(null);
         lName.setText(null);
         uName.setText(null);
         passbox.setText(null);
        if(cbVal.equals("Teacher")){
           tchName.setEnabled(true);
           fName.setEnabled(false);
          lName.setEnabled(false);
           userVal.setText("TCH" + "_");
           
       }else if(cbVal.equals("Select account type: ")){ 
           fName.setEnabled(false);
          lName.setEnabled(false);
       }else if(cbVal.equals("Admin")){
          fName.setEnabled(true);
          lName.setEnabled(true);
          tchName.setEnabled(false);
          userVal.setText("ADMIN" + "_");
        }else{
          fName.setEnabled(true);
          lName.setEnabled(true);
          tchName.setEnabled(false);
          userVal.setText(cbVal + "_");
        }
    }//GEN-LAST:event_USERNAMEActionPerformed

    private void lNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameActionPerformed

    }//GEN-LAST:event_lNameActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        
    }//GEN-LAST:event_fNameActionPerformed

    private void tchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tchNameActionPerformed

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void fNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameKeyTyped
              char c = evt.getKeyChar();
        
        if (Character.isDigit(c)) {
             evt.consume();
        }
    }//GEN-LAST:event_fNameKeyTyped

    private void fNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameKeyPressed

        
        
    }//GEN-LAST:event_fNameKeyPressed

    private void lNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameKeyTyped
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c)) {
             evt.consume();
        }
    }//GEN-LAST:event_lNameKeyTyped

    private void uNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uNameKeyTyped
        char c = evt.getKeyChar();
        
        if (Character.isDigit(c)) {
             evt.consume();
        }
    }//GEN-LAST:event_uNameKeyTyped

     public void getTeachers() {
    String getTC = "SELECT NAME FROM tchInfo";
    try {
        PreparedStatement applySQL = conn.prepareStatement(getTC);
        ResultSet tcVal = applySQL.executeQuery();
        
        System.out.println("All Rows:");
        while(tcVal.next()) {
            
            String tcName = tcVal.getString("NAME");
            System.out.println("FullName: " + tcName);
            tcModel.addElement(tcName);
        }
        
        applySQL.executeQuery();
        
        
    } catch (SQLException ex) {
        Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
    public void connectDB() throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); 
                if(conn != null){
                    System.out.println("Connectionn success");
                }
    }
    
   
    /**
     * @param args the command line arguments
     */
    
    public static void launch(String TCname) {
        TCHLANDING tl = new TCHLANDING(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITADDACCFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITADDACCFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITADDACCFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITADDACCFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ITName;
    private javax.swing.JComboBox<String> USERNAME;
    private javax.swing.JTable accTable;
    private javax.swing.JButton button;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName;
    private javax.swing.JLabel namefield;
    private javax.swing.JTextField passbox;
    private javax.swing.JComboBox<String> tchName;
    private javax.swing.JTextField uName;
    private javax.swing.JLabel userVal;
    // End of variables declaration//GEN-END:variables
}
