/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;

//Essential import classes

import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;


/**
 * 
 *
 * @author PC
 */
public final class loginviaSQ extends javax.swing.JFrame {

    
    /**
     * Creates new form login
     */
    public loginviaSQ(String value) {
        initComponents();      
            userName.setText(value);
            
            try {
                establishConnection(); //function calling
            } catch (SQLException ex) {
                Logger.getLogger(loginviaSQ.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(loginviaSQ.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            findUser();
            
            
        //Setting the icon    
        java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
          
        
        
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            
       
    }
//Variable initialization
        private Map<String, String> userDatabase = new HashMap<>();
    Connection conn;
    int i = 1;
   int x = 5;
   int limit = 4;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        ansBox = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        sqLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        userLbl1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(242, 239, 238));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        ansBox.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ansBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansBoxActionPerformed(evt);
            }
        });
        ansBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ansBoxKeyPressed(evt);
            }
        });
        getContentPane().add(ansBox);
        ansBox.setBounds(700, 440, 340, 50);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 42)); // NOI18N
        jLabel14.setText("EvalueNet");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(780, 170, 190, 40);

        userName.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        userName.setText("This is your username");
        getContentPane().add(userName);
        userName.setBounds(700, 290, 320, 16);

        sqLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        sqLabel.setText("This is the question you chose.");
        getContentPane().add(sqLabel);
        sqLabel.setBounds(700, 360, 360, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Answer");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(700, 400, 140, 21);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Security Question");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(700, 330, 140, 21);

        jButton2.setBackground(new java.awt.Color(0, 153, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN VIA SECURITY QUESTION");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 530, 250, 50);

        userLbl1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        userLbl1.setText("Username");
        getContentPane().add(userLbl1);
        userLbl1.setBounds(700, 260, 100, 16);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("EvalueNet V1.0");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 636, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("C.O.D.E.S");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1020, 640, 70, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lordz\\Downloads\\EvalueNet\\src\\EvalueNetPackage\\Blue and White Modern UI Login Page Deskstop Prototype (1).png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 800);

        setSize(new java.awt.Dimension(1296, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
         
    
    private void ansBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ansBoxKeyPressed
      
    }//GEN-LAST:event_ansBoxKeyPressed
        
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
             int closeApp = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
                    if(closeApp == JOptionPane.YES_OPTION) {
                            dispose();
                        } 
    }//GEN-LAST:event_formWindowClosing

    private void ansBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tempAccess();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void findUser(){
        
        
        String userVal = userName.getText();
            System.out.println(userVal);
        PreparedStatement getUser;
        try {
            getUser = conn.prepareStatement("SELECT username, SEC_QUES, ANS_SQ FROM tblaccounts WHERE username = ?");
                getUser.setString(1,userVal);
            ResultSet getValues = getUser.executeQuery();
                if(getValues.next()){
                    String sqVal = getValues.getString("SEC_QUES");
                        sqLabel.setText(sqVal);
                }
        } catch (SQLException ex) {
            Logger.getLogger(loginviaSQ.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
    }
    
    public void tempAccess(){
        String user = userName.getText();
        String sqVal = sqLabel.getText();
        String answer = ansBox.getText();
        if(answer.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your answer.");
        }else{
        try {
            PreparedStatement verify = conn.prepareStatement("SELECT username, ANS_SQ, SQ_Attempts FROM tblaccounts WHERE username = ?");
                verify.setString(1, user);
                ResultSet checkAns = verify.executeQuery();
    
                    if(checkAns.next()){
                        String ansVal = checkAns.getString("ANS_SQ");
                        int limitVal = checkAns.getInt("SQ_Attempts");
                            if(ansVal.equals(answer)){
                                if(limit > 0){
                                    PreparedStatement reduceAttempt = conn.prepareStatement("UPDATE tblaccounts SET SQ_Attempts =  SQ_Attempts - 1 WHERE username = ?");
                                        reduceAttempt.setString(1, user);
                                        reduceAttempt.executeUpdate();
                                        String getName = "SELECT FullName FROM tblaccounts WHERE username = ?";
                                        
                  if(user.contains("STUD")){
                    PreparedStatement getStudName = conn.prepareStatement(getName);
                    getStudName.setString(1, user);
                    ResultSet findStud = getStudName.executeQuery();
                    
                  if(findStud.next()){  
                    String studName = findStud.getString("FullName");
                    dispose();
                    Student s1 = new Student();
                    s1.studTitle.setText("Welcome, "+studName+"!");
                    s1.subTitle.setText(studName+"'s PROGRESS REPORT");
                    s1.setVisible(true);
                    
                  }
                }else if(user.contains("ADMIN")){
                     PreparedStatement getAdminName = conn.prepareStatement(getName);
                    getAdminName.setString(1, user);
                    ResultSet findAdmin = getAdminName.executeQuery();
                    
                    if(findAdmin.next()){
                        String adminName = findAdmin.getString("FullName");
                    dispose();
                    Admin a1 = new Admin(adminName);
                    resetAttempts();
                    a1.setVisible(true);
                    
                    }
                }else if(user.contains("TCH")){
                    PreparedStatement getTCName = conn.prepareStatement(getName);
                    getTCName.setString(1, user);
                    ResultSet findTC = getTCName.executeQuery();
                    
                    if(findTC.next()){
                    String TCname = findTC.getString("FullName");
                    TCHLANDING tl = new TCHLANDING(TCname);
                    
                    dispose();
                    resetAttempts();
                    tl.setVisible(true);
                    }
                }else if(user.contains("IT")){
                     PreparedStatement getITName = conn.prepareStatement(getName);
                    getITName.setString(1, user);
                    ResultSet findIT = getITName.executeQuery();
                    if(findIT.next()){
                    dispose();
                    String ITname = findIT.getString("FullName");
                    ITADDACC i1 = new ITADDACC(ITname);
                    
                   resetAttempts();
                    i1.setVisible(true);
                    }
                }else if(user.contains("HR")){
                    PreparedStatement getHRName = conn.prepareStatement(getName);
                    getHRName.setString(1, user);
                    ResultSet findHR = getHRName.executeQuery();
                    
                    if(findHR.next()){
                    dispose();
                    
                    String HRname = findHR.getString("FullName");
                    HRLANDING h1 = new HRLANDING(HRname);
                    
                    resetAttempts();
                    h1.setVisible(true);
                    }
                    }
                                }else{
                                    JOptionPane.showMessageDialog(null,"Try another account. You already used all attempt in this username.");
                                }
                            }else{
                                JOptionPane.showMessageDialog(null,"Incorrect answer, Please try again.");
                            }
                    }
        } catch (SQLException ex) {
            Logger.getLogger(loginviaSQ.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
                }
    
public void resetAttempts(){
        try {
            String user = userName.getText();
            PreparedStatement getUserAttempt = conn.prepareStatement("UPDATE tblaccounts SET logAttempt = 4 WHERE username = ?");
                getUserAttempt.setString(1, user);
                    getUserAttempt.executeUpdate();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


//Connecting Java to SQL server
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }

    public static void launch(String userVal) {
        loginviaSQ tl = new loginviaSQ(userVal);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginviaSQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginviaSQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginviaSQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginviaSQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ansBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel sqLabel;
    public javax.swing.JLabel userLbl1;
    public javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
