/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
/**
 *
 * @author lordz
 */
public class SECTIONSOG extends javax.swing.JFrame {

    /**
     * Creates new form SECTIONSOG
     */
    public SECTIONSOG(String sec, String sub, String tc) {
        initComponents();
        secLabel.setText(sec);
        subLabel.setText(sub);
        NAMETC.setText(tc);
        
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    
        
    }

    Connection conn;
    LocalDate latestDate = LocalDate.now();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        assessmentTbl = new javax.swing.JTable();
        secLabel = new javax.swing.JLabel();
        subLabel = new javax.swing.JLabel();
        adminTitle = new javax.swing.JLabel();
        NAMETC = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        finalTbl = new javax.swing.JTable();
        assessmentType = new javax.swing.JComboBox<>();
        SubmitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        latestSubmission = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        assessmentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "LRN", "Rating", "Percentage"
            }
        ));
        jScrollPane1.setViewportView(assessmentTbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(640, 50, 667, 314);

        secLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        secLabel.setText("SecName");
        getContentPane().add(secLabel);
        secLabel.setBounds(211, 118, 160, 30);

        subLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        subLabel.setText("SubName");
        getContentPane().add(subLabel);
        subLabel.setBounds(210, 110, 168, 108);

        adminTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle.setText("Welcome,");
        getContentPane().add(adminTitle);
        adminTitle.setBounds(211, 60, 90, 20);

        NAMETC.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        NAMETC.setText("Teacher Name");
        getContentPane().add(NAMETC);
        NAMETC.setBounds(211, 86, 268, 20);

        finalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LRN", "Name", "Initial Grade", "Transmuted Grade"
            }
        ));
        jScrollPane2.setViewportView(finalTbl);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(640, 400, 667, 320);

        assessmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select assessment type: ", "Quiz", "Peta", "Summative Exam", "Quarterly Exam" }));
        getContentPane().add(assessmentType);
        assessmentType.setBounds(490, 140, 110, 39);

        SubmitBtn.setText("Find");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(490, 190, 110, 42);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("NOTE: Make sure the grades from all assessments are already submitted to show their transmuted and initial grade");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(680, 720, 642, 16);

        jButton3.setText("Submit Final Grades");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(520, 590, 135, 23);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(399, 438, 72, 23);

        jButton2.setText("Submit ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(510, 250, 72, 23);

        jButton4.setText("Get Grades");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(490, 440, 129, 23);

        latestSubmission.setText("jLabel2");
        getContentPane().add(latestSubmission);
        latestSubmission.setBounds(670, 20, 667, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        int assVal =  assessmentType.getSelectedIndex();
           if(assVal == 0){ 
                JOptionPane.showMessageDialog(null,"Please select a subject.");
           }else{
               getScores();
           }    
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        submitGrades();
        submitInitialTransmuted();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = NAMETC.getText();
        
                TCHSUMMARY ta = new TCHSUMMARY(name);
                      
        
        ta.setVisible(true);
        this.setVisible(false);
       

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           getStudents();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        submitGrades();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void submitGrades() {
    DefaultTableModel TableVal = (DefaultTableModel) assessmentTbl.getModel();
    String secVal = secLabel.getText();
    String subVal = subLabel.getText();
    String assType = (String) assessmentType.getSelectedItem();

    try {
        PreparedStatement applySQL = conn.prepareStatement(
            "INSERT INTO finalGrades(LRN, Name, Section, Subject, rating, percentage, assessmentType) " +
            "VALUES (?, ?, ?, ?, ?, ?, ?) " +
            "ON DUPLICATE KEY UPDATE rating = VALUES(rating), percentage = VALUES(percentage);"
        );

        for (int rowIndex = 0; rowIndex < assessmentTbl.getRowCount(); rowIndex++) {
            double rating = (double) TableVal.getValueAt(rowIndex, 2);
            double percentage = (double) TableVal.getValueAt(rowIndex, 3);
            String lrn = (String) TableVal.getValueAt(rowIndex, 1);
            String name = (String) TableVal.getValueAt(rowIndex, 0);
            System.out.println("LRN: " + lrn + " NAME: " + name + " RATING: " + rating + " PERCENTAGE: " + percentage);

            applySQL.setString(1, lrn);
            applySQL.setString(2, name);
            applySQL.setString(3, secVal);
            applySQL.setString(4, subVal);
            applySQL.setDouble(5, rating);
            applySQL.setDouble(6, percentage);
            applySQL.setString(7, assType);
            applySQL.addBatch();
        }

        applySQL.executeBatch();
        JOptionPane.showMessageDialog(null,"The grades for "+assType+" has been submitted successfully");
        
        latestSubmission.setText("The grades was last submitted on "+latestDate);
        
    } catch (SQLException ex) {
        Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error updating information: " + ex.getMessage());
    }
}
    
  public void getStudents() {
    String secVal = secLabel.getText();
    String subVal = subLabel.getText();
        
    
    try {
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM finalGrades WHERE Section = ? AND Subject= ?"
        );

        getAssessment.setString(1, secVal);
        getAssessment.setString(2, subVal);

        ResultSet getStud = getAssessment.executeQuery();

        // Clear the table model before adding new data
        DefaultTableModel AssignScore = (DefaultTableModel) finalTbl.getModel();
        AssignScore.setRowCount(0);

        // Use a set to track LRNs that have been added
        Set<String> addedLRNs = new HashSet<>();

        while (getStud.next()) {
            String studentLRN = getStud.getString("LRN");
            String studentName = getStud.getString("Name");

            // Check if the student is already added
            if (!addedLRNs.contains(studentLRN)) {
                // Create a new row and populate student details
                Object[] row = new Object[AssignScore.getColumnCount()];
                row[0] = studentLRN;  // Set student LRN
                row[1] = studentName; // Set student name

                // Add the row to the table model
                AssignScore.addRow(row);

                // Mark the LRN as added
                addedLRNs.add(studentLRN);
            }
        }
            getInitialTransmuted();
    } catch (SQLException ex) {
        Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
    }
}


   public void getInitialTransmuted() {
    try {
        String sec = secLabel.getText();
        String sub = subLabel.getText();
        
        // Query to get all grades for the specified section and subject
        PreparedStatement getStudent = conn.prepareStatement("SELECT LRN, percentage FROM finalGrades WHERE Section = ? AND Subject = ?");
        getStudent.setString(1, sec);
        getStudent.setString(2, sub);
        
        ResultSet getVal = getStudent.executeQuery();
        Map<String, Double> initialGrade = new LinkedHashMap<>();
        int count = 0;

        // Iterate through the result set
        while (getVal.next()) {
            String studLRN = getVal.getString("LRN");
            double percentVal = getVal.getDouble("percentage");

            // Sum the percentages for the same LRN
            initialGrade.put(studLRN, initialGrade.getOrDefault(studLRN, 0.0) + percentVal);
            count++;
        }
        
        System.out.println("Number of records: " + count);
        Map<String, Map<Double,Double>> finalGrades = new LinkedHashMap<>();
        double transmutedGrade = 0.0;
        // Print the results
        for (Map.Entry<String, Double> entry : initialGrade.entrySet()) {
            String studentLRN = entry.getKey();
            double iniGrade = entry.getValue();
            System.out.println("LRN: " + studentLRN + " TOTAL GRADE: " + iniGrade);
            System.out.println("");
        
            if (iniGrade > 99.99) {
            transmutedGrade = 100;
        } else if (iniGrade > 98.39) {
            transmutedGrade =99;
        } else if (iniGrade > 96.79) {
            transmutedGrade =98;
        } else if (iniGrade > 95.19) {
           transmutedGrade =97;
        } else if (iniGrade > 93.59) {
            transmutedGrade =96;
        } else if (iniGrade > 91.99) {
            transmutedGrade =95;
        } else if (iniGrade > 90.39) {
            transmutedGrade =94;
        } else if (iniGrade > 88.79) {
            transmutedGrade =93;
        } else if (iniGrade > 87.19) {
            transmutedGrade =92;
        } else if (iniGrade > 85.59) {
            transmutedGrade =91;
        } else if (iniGrade > 83.99) {
            transmutedGrade =90;
        } else if (iniGrade > 82.39) {
            transmutedGrade =89;
        } else if (iniGrade > 80.79) {
            transmutedGrade =88;
        } else if (iniGrade > 79.19) {
            transmutedGrade =87;
        } else if (iniGrade > 77.59) {
            transmutedGrade =86;
        } else if (iniGrade > 75.99) {
            transmutedGrade =85;
        } else if (iniGrade > 74.39) {
            transmutedGrade =84;
        } else if (iniGrade > 72.79) {
            transmutedGrade =83;
        } else if (iniGrade > 71.19) {
            transmutedGrade =82;
        } else if (iniGrade > 69.59) {
            transmutedGrade =81;
        } else if (iniGrade > 67.99) {
            transmutedGrade =80;
        } else if (iniGrade > 66.39) {
            transmutedGrade =79;
        } else if (iniGrade > 64.79) {
            transmutedGrade =78;
        } else if (iniGrade > 63.19) {
            transmutedGrade =77;
        } else if (iniGrade > 61.59) {
            transmutedGrade =76;
        } else if (iniGrade > 59.99) {
            transmutedGrade =75;
        } else if (iniGrade > 55.99) {
            transmutedGrade =74;
        } else if (iniGrade > 51.99) {
            transmutedGrade =73;
        } else if (iniGrade > 47.99) {
            transmutedGrade =72;
        } else if (iniGrade > 43.99) {
            transmutedGrade =71;
        } else if (iniGrade > 39.99) {
            transmutedGrade =70;
        } else if (iniGrade > 35.99) {
            transmutedGrade =69;
        } else if (iniGrade > 31.99) {
            transmutedGrade =68;
        } else if (iniGrade > 27.99) {
            transmutedGrade =67;
        } else if (iniGrade > 23.99) {
            transmutedGrade =66;
        } else if (iniGrade > 19.99) {
            transmutedGrade =65;
        } else if (iniGrade > 15.99) {
            transmutedGrade =64;
        } else if (iniGrade > 11.99) {
            transmutedGrade =63;
        } else if (iniGrade > 7.99) {
            transmutedGrade =62;
        } else if (iniGrade > 3.99) {
            transmutedGrade =61;
        } else if (iniGrade >= 0) {
            transmutedGrade =60;
        } else {
            transmutedGrade = 0; // Handle negative values if needed
        }
            
            System.out.println("LRN: "+studentLRN+" INITIAL GRADE: "+iniGrade+" TRANSMUTED GRADE: "+transmutedGrade );
            Map<Double,Double> getGrades = new LinkedHashMap<>();
                getGrades.put(iniGrade, transmutedGrade);
                    finalGrades.put(studentLRN, getGrades);
            
        }
        
        
        
        for (int row = 0; row < finalTbl.getRowCount(); row++) {
            String LRN = (String) finalTbl.getValueAt(row, 0); // Get the LRN from the first column
            if (finalGrades.containsKey(LRN)) {
                Map<Double, Double> fGrades = finalGrades.get(LRN);
                Map.Entry<Double, Double> firstGrade = fGrades.entrySet().iterator().next();
                finalTbl.setValueAt(firstGrade.getKey(), row, 2); // Set Rating in third column
                finalTbl.setValueAt(firstGrade.getValue(), row, 3); // Set Percentage in fourth column
            }
        }
        
        
        
    } catch (SQLException ex) {
        Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
   public void submitInitialTransmuted(){
        DefaultTableModel TableVal = (DefaultTableModel) finalTbl.getModel();
    String secVal = secLabel.getText();
    String subVal = subLabel.getText();
    String assType = (String) assessmentType.getSelectedItem();

    try {
        PreparedStatement applySQL = conn.prepareStatement(
            "INSERT INTO cardGrades(LRN, Name, SecVal, SubVal, initialGrade, transmutedGrade) " +
            "VALUES (?, ?, ?, ?, ?, ?) " +
            "ON DUPLICATE KEY UPDATE initialGrade = VALUES(initialGrade), transmutedGrade = VALUES(transmutedGrade);"
        );

        for (int rowIndex = 0; rowIndex < finalTbl.getRowCount(); rowIndex++) {
            double initialGrade = (double) TableVal.getValueAt(rowIndex, 2);
            double transmutedGrade = (double) TableVal.getValueAt(rowIndex, 3);
            String lrn = (String) TableVal.getValueAt(rowIndex, 0);
            String name = (String) TableVal.getValueAt(rowIndex, 1);
            

            applySQL.setString(1, lrn);
            applySQL.setString(2, name);
            applySQL.setString(3, secVal);
            applySQL.setString(4, subVal);
            applySQL.setDouble(5, initialGrade);
            applySQL.setDouble(6, transmutedGrade);
            applySQL.addBatch();
        }

        applySQL.executeBatch();
        JOptionPane.showMessageDialog(null, "Information updated successfully!");
    } catch (SQLException ex) {
        Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error updating information: " + ex.getMessage());
    }
   }
    
    public void getScores() {
        String secVal = secLabel.getText();
       
       String subVal = subLabel.getText();
    try {
        String assType = (String) assessmentType.getSelectedItem();
        
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ? "
        );

        getAssessment.setString(1, secVal);
        getAssessment.setString(2, subVal);
        getAssessment.setString(3, assType);
        
        

        ResultSet getQuiz = getAssessment.executeQuery();

        // Clear the table model once, before processing any quizzes
        DefaultTableModel AssignScore = (DefaultTableModel) assessmentTbl.getModel();
        AssignScore.setRowCount(0);
        int columnIndex = 2; // Assuming first two columns are for student name and LRN

        if(getQuiz.next()) {
            String AID = getQuiz.getString("assessment_id");
            String QN = getQuiz.getString("assessmentNum");
            
           
            PreparedStatement scores = conn.prepareStatement(
                "SELECT studNAME, studLRN, score, assessmentID FROM tblscores WHERE assessmentID = ?"
            );
            scores.setString(1, AID);
            ResultSet scoreVal = scores.executeQuery();
            
            while (scoreVal.next()) {
                String studentLRN = scoreVal.getString("studLRN");
                String studentName = scoreVal.getString("studNAME");
                
                    
                
                    // If the student is not in the map, create a new row and add student details
                    Object[] row = new Object[AssignScore.getColumnCount()];
                    row[0] = studentName; // Set student name
                    row[1] = studentLRN;  // Set student LRN
                    

                    // Store this row in the map
                    
                    AssignScore.addRow(row); // Add the new row to the table model
                    
                    
            }
                    
                     getFinalGrades();  
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
    
   public void getFinalGrades(){
       int percentage = 0;
        String aType = (String)assessmentType.getSelectedItem();
    
       if ("Peta".equals(aType)) {
        percentage = 40;
    } else {
        percentage = 20;
    }
      String secVal = secLabel.getText();
       
       String subVal = subLabel.getText();
       try {
          
           
           
           
        DefaultTableModel AssignRP = (DefaultTableModel) assessmentTbl.getModel();
        double totalItems = 0;
        
        
        String quiz = (String) assessmentType.getSelectedItem();
        
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ?"
        );

        getAssessment.setString(1, secVal);
        getAssessment.setString(2, subVal);
        getAssessment.setString(3, quiz);

        ResultSet getQuiz = getAssessment.executeQuery();

        // Collect all quizzes
        Map<String, String> quizMap = new LinkedHashMap<>(); // QuizNum -> AssessmentID
        while (getQuiz.next()) {
            String assessmentID = getQuiz.getString("assessment_id");
            String quizNum = getQuiz.getString("assessmentNum");
            int totalItm = getQuiz.getInt("totalItems");
            totalItems += totalItm;
            quizMap.put(quizNum, assessmentID);
        }
        
        System.out.println("Section: " + secVal + " Subject: " + subVal + " Total Score: " + totalItems);

        // Collect all student scores
        Map<String, Map<String, Integer>> studentScores = new LinkedHashMap<>(); // LRN -> {QuizNum -> Score}
        Map<String, Integer> totalScores = new LinkedHashMap<>(); // LRN -> Total Score

        for (Map.Entry<String, String> entry : quizMap.entrySet()) {
            String quizNum = entry.getKey();
            String assessmentID = entry.getValue();

            PreparedStatement scores = conn.prepareStatement(
                "SELECT studNAME, studLRN, score FROM tblscores WHERE assessmentID = ?"
            );
            scores.setString(1, assessmentID);
            ResultSet scoreVal = scores.executeQuery();

            while (scoreVal.next()) {
                String studentLRN = scoreVal.getString("studLRN");
                int score = scoreVal.getInt("score");

                // Add or update the student's scores
                studentScores.putIfAbsent(studentLRN, new LinkedHashMap<>());
                studentScores.get(studentLRN).put(quizNum, score);
                
                // Update the total score for the student
                totalScores.putIfAbsent(studentLRN, 0); // Initialize total score if not present
                totalScores.put(studentLRN, totalScores.get(studentLRN) + score); // Add the current score to total
            }
        }

        // Prepare final grades
        Map<String, Map<Double, Double>> finalGrades = new LinkedHashMap<>(); // LRN -> {Rating -> Percentage}
        StringBuilder output = new StringBuilder("Final Grades:\n\n");

        for (Map.Entry<String, Map<String, Integer>> studentEntry : studentScores.entrySet()) {
            String studentLRN = studentEntry.getKey();
            double totalScore = totalScores.get(studentLRN);
            double ratingVal = (totalScore / totalItems) * 100;
            double percentVal = ratingVal * percentage / 100;

            output.append("Student LRN: ").append(studentLRN).append("\n");
            output.append("  Total Score: ").append(totalScore).append("\n");
            output.append("  Rating: ").append(ratingVal).append("\n");
            output.append("  Percentage: ").append(percentVal).append("\n\n");

            System.out.println("Student: " + studentLRN + " Rating: " + ratingVal + " Percentage: " + percentVal);

            Map<Double, Double> grades = new LinkedHashMap<>();
            grades.put(ratingVal, percentVal);
            finalGrades.put(studentLRN, grades);
        }

        // Update the table
        for (int row = 0; row < AssignRP.getRowCount(); row++) {
            String LRN = (String) AssignRP.getValueAt(row, 1); // Get the LRN from the first column
            if (finalGrades.containsKey(LRN)) {
                Map<Double, Double> fGrades = finalGrades.get(LRN);
                Map.Entry<Double, Double> firstGrade = fGrades.entrySet().iterator().next();
                AssignRP.setValueAt(firstGrade.getKey(), row, 2); // Set Rating in third column
                AssignRP.setValueAt(firstGrade.getValue(), row, 3); // Set Percentage in fourth column
            }
        }

        // Output in a dialog box
        

        // Optionally, output to the console
        System.out.println(output);

    } catch (SQLException ex) {
        Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
    }
   }
    
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    public static void launch(String Sec,String Sub, String tc) {
        SECTIONSOG tl = new SECTIONSOG(Sec,Sub,tc);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SECTIONSOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SECTIONSOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SECTIONSOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SECTIONSOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel NAMETC;
    private javax.swing.JButton SubmitBtn;
    public javax.swing.JLabel adminTitle;
    private javax.swing.JTable assessmentTbl;
    private javax.swing.JComboBox<String> assessmentType;
    private javax.swing.JTable finalTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel latestSubmission;
    public javax.swing.JLabel secLabel;
    public javax.swing.JLabel subLabel;
    // End of variables declaration//GEN-END:variables
}
