        /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;


import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author aicel
 */
public class tablestudent extends javax.swing.JFrame {

    /**
     * Creates new form tablestudent
     */
    public tablestudent(String val) {
        initComponents();
        adminName.setText(val);
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        //Setting the icon    
        java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
          
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        studTable.setDefaultEditor(Object.class, null);
    }

    Connection conn;
    DefaultComboBoxModel<String> secListModel = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> value = new DefaultComboBoxModel<>();
    
    
     public void getItem(){
         String tblVal =(String) tblFilter.getSelectedItem();
         int valNum = tblFilter.getSelectedIndex();
         if(valNum != 0){
             try {    
                 PreparedStatement getSec = conn.prepareStatement("SELECT LRN,NAME,STRAND,Section_Assigned FROM sf1_db WHERE STRAND = ?");
                    getSec.setString(1,tblVal);
                    ResultSet findSection = getSec.executeQuery();
                         ResultSetMetaData getColVal = (ResultSetMetaData) findSection.getMetaData();
            int q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) studTable.getModel();
            secAssign.setRowCount(0);
            while (findSection.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = findSection.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
             } catch (SQLException ex) {
                 Logger.getLogger(tablesf1.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else{
             JOptionPane.showMessageDialog(null,"Please choose a strand first");
         }
               
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        secList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        adminTitle1 = new javax.swing.JLabel();
        adminName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tblFilter = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        studTable.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LRN", "Student", "Strand", "Section"
            }
        ));
        studTable.setRowHeight(23);
        studTable.setShowGrid(true);
        studTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 230, 1080, 140);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 440, 10, 0);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1070, 500, 120, 40);

        secList.setModel(secListModel);
        secList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secListActionPerformed(evt);
            }
        });
        getContentPane().add(secList);
        secList.setBounds(1010, 420, 190, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("View Class List");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(490, 140, 330, 50);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText(" Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(940, 500, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setText("Assign a Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1030, 390, 170, 30);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton5.setText("LOG OUT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1100, 50, 110, 40);

        adminTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle1.setText("Welcome, ");
        getContentPane().add(adminTitle1);
        adminTitle1.setBounds(160, 50, 90, 20);

        adminName.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminName.setText("Admin!");
        getContentPane().add(adminName);
        adminName.setBounds(250, 50, 150, 20);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Search Filter:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(220, 460, 130, 21);

        tblFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select specialization:  ", "ICT", "HE", "GAS", "ABM" }));
        tblFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblFilterActionPerformed(evt);
            }
        });
        getContentPane().add(tblFilter);
        tblFilter.setBounds(200, 500, 140, 30);

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 550, 72, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1280, 800);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1296, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void secListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secListActionPerformed

    private void studTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studTableMouseClicked
        sectionMgmt();
    }//GEN-LAST:event_studTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel secAssign = (DefaultTableModel) studTable.getModel();     
        int selectedRow = studTable.getSelectedRow();
                    if(selectedRow != -1){   
                        String secVal = (String) secList.getSelectedItem();
                        int colIndex = 3;
                        secAssign.setValueAt(secVal, selectedRow,colIndex);
                        System.out.println("Value from Column " + colIndex + ": " + secAssign); 
                    }
                    secUpdate();
                    
        
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ClassAdd sa = new ClassAdd(adminName.getText());
        sa.setVisible(true);
        sa.adminTitle.setText(adminName.getText());
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
         int closeApp = JOptionPane.showConfirmDialog(this, "Are you sure you want to Exit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
                    if(closeApp == JOptionPane.YES_OPTION) {
                            dispose();
                        } 
    }//GEN-LAST:event_formWindowClosing

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            dispose();
            l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblFilterActionPerformed
        
    }//GEN-LAST:event_tblFilterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getItem();
    }//GEN-LAST:event_jButton2ActionPerformed

    /*public void getTblVal(){
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT LRN, NAME, STRAND, Section_Assigned FROM sf1_db ");
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) studTable.getModel();
            studTable.setDefaultEditor(Object.class, null);
            
            secAssign.setRowCount(0);
            while (getValues.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = getValues.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    

                    
         public void sectionMgmt(){
             DefaultTableModel secAssign = (DefaultTableModel) studTable.getModel();
                int selectedRow = studTable.getSelectedRow();
                    if(selectedRow != -1){
                         int modelRowIndex = studTable.convertRowIndexToModel(selectedRow);
                        int columnIndex = 2;
                        String chooseStrand = secAssign.getValueAt(modelRowIndex,columnIndex).toString();
                        System.out.println("Value from Column " + columnIndex + ": " + chooseStrand);
     
                secList.removeAllItems();
        
        if(chooseStrand.equals("ICT") ){
            try {
                String ictStrand = "SELECT SctnName FROM ictsections";
                PreparedStatement getICT = conn.prepareStatement(ictStrand);
                ResultSet getSection = getICT.executeQuery();
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else if(chooseStrand.equals("HE") ){
            try {
                String heStrand = "SELECT SctnName FROM hesections";      //Change strand
                PreparedStatement getHE = conn.prepareStatement(heStrand); //Change strand
                ResultSet getSection = getHE.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("GAS") ){
            try {
                String gasStrand = "SELECT SctnName FROM gassections";      //Change strand
                PreparedStatement getGAS = conn.prepareStatement(gasStrand); //Change strand
                ResultSet getSection = getGAS.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("ABM") ){
            try {
                String abmStrand = "SELECT SctnName FROM abmsections";      //Change strand
                PreparedStatement getABM = conn.prepareStatement(abmStrand); //Change strand
                ResultSet getSection = getABM.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secListModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
         }
         }
         
         public void secUpdate(){
    DefaultTableModel TableVal = (DefaultTableModel) studTable.getModel();    
    String updVal = "UPDATE sf1_db SET Section_Assigned = ? WHERE LRN = ?";

    try (PreparedStatement applySQL = conn.prepareStatement(updVal)) {
        for (int rowIndex = 0; rowIndex < TableVal.getRowCount(); rowIndex++) {
            String classVal = (String) TableVal.getValueAt(rowIndex, 3);
            String lrnVal = (String) TableVal.getValueAt(rowIndex, 0);     
            
            if (classVal != null && !classVal.isEmpty()) {
                
                applySQL.setString(1, classVal);
                applySQL.setString(2, lrnVal); 
                applySQL.addBatch(); 
            }
        }
        applySQL.executeBatch(); 
        JOptionPane.showMessageDialog(null, "Information updated successfully!");
    } catch (SQLException ex) {
        Logger.getLogger(tablesf1.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error updating information: " + ex.getMessage());
    }
         }
    
         
         
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void launch(String adminName) {
        tablestudent tl = new tablestudent(adminName);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablestudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablestudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablestudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablestudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               launch("");
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminName;
    public javax.swing.JLabel adminTitle1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> secList;
    private javax.swing.JTable studTable;
    private javax.swing.JComboBox<String> tblFilter;
    // End of variables declaration//GEN-END:variables
}
