 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.Query.value;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aicel
 */
public class TCHLASTPAGE extends javax.swing.JFrame {

    /**
     * Creates new form TCHLASTPAGE
     */
    public TCHLASTPAGE(String Secvalue, String Subvalue) {
        initComponents();
        
        sec.setText(Secvalue);
        sub.setText(Subvalue);
        
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        totalitems.setEnabled(false);
        month.setEnabled(false);
        day.setEnabled(false);
        year.setEnabled(false);
        jButton12.setEnabled(false);
        
       
        
    }

    Connection conn;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gradingSheet = new javax.swing.JTable();
        sec = new javax.swing.JLabel();
        sub = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tcVal = new javax.swing.JLabel();
        adminTitle = new javax.swing.JLabel();
        assType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalitems = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        AssNum = new javax.swing.JLabel();
        AssType = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ANUM = new javax.swing.JComboBox<>();
        ATYPE = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton7.setBackground(new java.awt.Color(204, 255, 204));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton7.setText("Get Grades");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(550, 560, 140, 30);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton3.setText("LOG OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1100, 50, 110, 40);

        gradingSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LRN", "Name", "Scores", "Total Items"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(gradingSheet);
        if (gradingSheet.getColumnModel().getColumnCount() > 0) {
            gradingSheet.getColumnModel().getColumn(2).setPreferredWidth(8);
            gradingSheet.getColumnModel().getColumn(3).setPreferredWidth(3);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(550, 150, 710, 260);

        sec.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        sec.setText(null);
        getContentPane().add(sec);
        sec.setBounds(30, 130, 150, 27);

        sub.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        sub.setText("SubName");
        getContentPane().add(sub);
        sub.setBounds(30, 160, 110, 21);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1030, 530, 110, 40);

        jButton2.setText("Peta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 260, 90, 30);

        jButton4.setText("Summative");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 300, 90, 30);

        jButton5.setText("Periodical");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 340, 90, 30);

        jButton6.setText("Quiz");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 220, 90, 30);

        jLabel2.setText("View Assessment List:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 380, 140, 20);

        tcVal.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        tcVal.setText("Maria Aurea Reyes Jabon");
        getContentPane().add(tcVal);
        tcVal.setBounds(270, 50, 330, 20);

        adminTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle.setText("Welcome,");
        getContentPane().add(adminTitle);
        adminTitle.setBounds(170, 50, 90, 20);

        assType.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        assType.setText("Assessment No. :");
        getContentPane().add(assType);
        assType.setBounds(180, 340, 180, 20);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel5.setText("Date:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 270, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel4.setText("Items:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 200, 80, 20);

        totalitems.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        totalitems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalitemsActionPerformed(evt);
            }
        });
        totalitems.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalitemsKeyTyped(evt);
            }
        });
        getContentPane().add(totalitems);
        totalitems.setBounds(250, 190, 120, 30);

        year.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", " " }));
        getContentPane().add(year);
        year.setBounds(460, 260, 79, 30);

        month.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(250, 260, 120, 30);

        day.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day);
        day.setBounds(380, 260, 70, 30);

        AssNum.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(AssNum);
        AssNum.setBounds(370, 340, 70, 30);

        AssType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AssType.setText("Assessment Type");
        getContentPane().add(AssType);
        AssType.setBounds(300, 140, 160, 30);

        jLabel3.setText("Add a new assessment:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 190, 140, 20);

        jButton8.setText("GO TO EXAM LIST");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 410, 170, 40);

        jButton9.setText("GO TO QUIZ LIST");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 460, 170, 40);

        jButton10.setText("GO TO PETA LIST");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 510, 170, 40);

        jButton11.setText("GO TO EXAM LIST");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(10, 560, 170, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Assessment Num:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 510, 110, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Modify Grades");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 420, 130, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Assessment Type:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(520, 460, 110, 30);

        ANUM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select assessment number:","1", "2", "3", "4","5","6","7" }));
        getContentPane().add(ANUM);
        ANUM.setBounds(630, 510, 80, 30);

        ATYPE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz", "Peta", "Summative Exam", "Quarterly Exam" }));
        getContentPane().add(ATYPE);
        ATYPE.setBounds(630, 460, 80, 30);

        jButton12.setBackground(new java.awt.Color(204, 255, 204));
        jButton12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton12.setText("Save");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(300, 380, 110, 40);

        jButton13.setBackground(new java.awt.Color(204, 255, 204));
        jButton13.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton13.setText("Submit");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(1150, 530, 110, 40);

        setSize(new java.awt.Dimension(1294, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
        dispose();
        l1.setVisible(true);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        TCHLANDING tl = new TCHLANDING(tcVal.getText());
        
        this.setVisible(false);
        tl.setVisible(true);
               
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     getPeta();
     totalitems.setEnabled(true);
        month.setEnabled(true);
        day.setEnabled(true);
        year.setEnabled(true);
        jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //QUIZ
            getQuiz();
            totalitems.setEnabled(true);
        month.setEnabled(true);
        day.setEnabled(true);
        year.setEnabled(true);
        jButton12.setEnabled(true);    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  getSE();
  totalitems.setEnabled(true);
        month.setEnabled(true);
        day.setEnabled(true);
        year.setEnabled(true);
        jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       getQE();
       totalitems.setEnabled(true);
        month.setEnabled(true);
        day.setEnabled(true);
        year.setEnabled(true);
        jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       
      getStudVal();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SummativeExamList pel = new SummativeExamList();
        pel.secName.setText(sec.getText());
        pel.subName.setText(sub.getText());
        pel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String secVal = sec.getText();
        String subVal = sub.getText();
        
        QuizList ql = new QuizList(secVal,subVal);
        ql.setVisible(true);
        this.setVisible(false);
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        PetaList pl = new PetaList();
        pl.secName.setText(sec.getText());
        pl.subName.setText(sub.getText());
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        PeriodicExamList pel = new PeriodicExamList();
        pel.secName.setText(sec.getText());
        pel.subName.setText(sub.getText());
        pel.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        getTblVal(); 
        addValues();
        addTotalItems();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void totalitemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalitemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalitemsActionPerformed

    private void totalitemsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalitemsKeyTyped
          char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
            
        }         
    }//GEN-LAST:event_totalitemsKeyTyped

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    public void getQuiz(){
        AssType.setText("Quiz");
        assType.setText("Quiz No: ");
        try {
            PreparedStatement getLastNum = conn.prepareStatement("SELECT assessmentNum \n" +
"FROM tblassessment \n" +
"WHERE className = ? AND subjectName = ? AND assessmentType = ? \n" +
"ORDER BY assessmentNum DESC \n" +
"LIMIT 1;");
        getLastNum.setString(1,sec.getText());
        getLastNum.setString(2,sub.getText());
        getLastNum.setString(3,"Quiz");
            ResultSet findLN = getLastNum.executeQuery();
                if(findLN.next()){
                        String lnVal = findLN.getString("assessmentNum");
                            int lastAN = Integer.parseInt(lnVal);
                            
                                lastAN = lastAN + 1;
                                
                                String finalVal = String.valueOf(lastAN);
                                
                                AssNum.setText(finalVal);
                }
                
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getPeta(){
        AssType.setText("Peta");
        assType.setText("Peta No: ");
        try {
            PreparedStatement getLastNum = conn.prepareStatement("SELECT assessmentNum \n" +
"FROM tblassessment \n" +
"WHERE className = ? AND subjectName = ? AND assessmentType = ? \n" +
"ORDER BY assessmentNum DESC \n" +
"LIMIT 1;");
        getLastNum.setString(1,sec.getText());
        getLastNum.setString(2,sub.getText());
        getLastNum.setString(3,"Peta");
            ResultSet findLN = getLastNum.executeQuery();
                if(findLN.next()){
                        String lnVal = findLN.getString("assessmentNum");
                            int lastAN = Integer.parseInt(lnVal);
                            
                                lastAN = lastAN + 1;
                                
                                String finalVal = String.valueOf(lastAN);
                                
                                AssNum.setText(finalVal);
                }
                
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getSE(){
        AssType.setText("Summative Exam");
        assType.setText("Summative Exam No: ");
        try {
            PreparedStatement getLastNum = conn.prepareStatement("SELECT assessmentNum \n" +
"FROM tblassessment \n" +
"WHERE className = ? AND subjectName = ? AND assessmentType = ? \n" +
"ORDER BY assessmentNum DESC \n" +
"LIMIT 1;");
        getLastNum.setString(1,sec.getText());
        getLastNum.setString(2,sub.getText());
        getLastNum.setString(3,"Summative Exam");
            ResultSet findLN = getLastNum.executeQuery();
                if(findLN.next()){
                        String lnVal = findLN.getString("assessmentNum");
                            int lastAN = Integer.parseInt(lnVal);
                            
                                lastAN = lastAN + 1;
                                
                                String finalVal = String.valueOf(lastAN);
                                
                                AssNum.setText(finalVal);
                }
                
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void getQE(){
        AssType.setText("Quarterly Exam");
        assType.setText("Quarterly Exam No: ");
        try {
            PreparedStatement getLastNum = conn.prepareStatement("SELECT assessmentNum \n" +
"FROM tblassessment \n" +
"WHERE className = ? AND subjectName = ? AND assessmentType = ? \n" +
"ORDER BY assessmentNum DESC \n" +
"LIMIT 1;");
        getLastNum.setString(1,sec.getText());
        getLastNum.setString(2,sub.getText());
        getLastNum.setString(3,"Quarterly Exam");
            ResultSet findLN = getLastNum.executeQuery();
                if(findLN.next()){
                        String lnVal = findLN.getString("assessmentNum");
                            int lastAN = Integer.parseInt(lnVal);
                            
                                lastAN = lastAN + 1;
                                
                                String finalVal = String.valueOf(lastAN);
                                
                                AssNum.setText(finalVal);
                }
                
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
     public void getTblVal(){
          String secVal = sec.getText();
          String subVal = sub.getText();
          
          System.out.println("I HAVE FOUND THE SECTION: "+secVal);
          
          String assessment = assType.getText();
          
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT LRN, NAME,Section_Assigned FROM sf1_db WHERE Section_Assigned = ?");
                pstmt.setString(1,secVal);
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) gradingSheet.getModel();
                        
            secAssign.setRowCount(0);
            while (getValues.next()) {
                    String LRN = getValues.getString("LRN");
                    String total = totalitems.getText();
                    Object[] row = new Object[2];
                
                for (int i = 1; i <= 2; i++) {
                    row[i - 1] = getValues.getObject(i);
                    
                }
                secAssign.addRow(row); // Add the row to the table model
                
               
            }
            
        
                
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
      public void insertVal(){
    String Sec = sec.getText();
        String Sub = sub.getText();
        
        String insertSecSub = "INSERT INTO tblassessment(className, subjectName) VALUES(?,?)";
        
        try {
            PreparedStatement applyIns = conn.prepareStatement(insertSecSub);
                applyIns.setString(1,Sec);
                applyIns.setString(2,Sub);
            applyIns.executeUpdate();
            System.out.println("Section: "+Sec+" and "+"Subject: "+Sub);
               
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }                      
}
    
    public void insertSE(){
         
         String secValue = sec.getText();
         String subValue = sub.getText();
            System.out.println(secValue);
            System.out.println(subValue);
         String assType = AssType.getText();
         String slctVal = "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ?";
        try {
            PreparedStatement getVal = conn.prepareStatement(slctVal);
            getVal.setString(1, secValue);
            getVal.setString(2, subValue);
            ResultSet findVal = getVal.executeQuery();
                if(findVal.next()){
                    int idVal = findVal.getInt("assessment_id");
                     System.out.println("Values found!");
                     String quizSQL = "UPDATE tblassessment SET assessmentType = ? WHERE assessmentType IS NULL";       
        try {
            PreparedStatement applySQL = conn.prepareStatement(quizSQL);
            applySQL.setString(1,assType);
            
            applySQL.executeUpdate();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
                 
                }
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
public void addValues(){
            insertVal();
            
         insertSE();
            
            String getTotal = totalitems.getText();
                String getMonth = (String) month.getSelectedItem();
                String getDay = (String) day.getSelectedItem();
                String getYear = (String) year.getSelectedItem();
                String dateVal = getYear + "-" + getMonth + "-" + getDay;
            String quizNum = AssNum.getText();

            String sec = this.sec.getText();
            String sub = this.sub.getText();

            try {
               PreparedStatement getVal = conn.prepareStatement( "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ?");
               getVal.setString(1,sec);
               getVal.setString(2,sub);
                ResultSet findVal = getVal.executeQuery();
                    if(findVal.next()){
                      String getCN = findVal.getString("assessmentNum");
                      String getSN = findVal.getString("totalItems");                  
                      String getAD = findVal.getString("assessmentDate");                  
                      int idVal = findVal.getInt("assessment_id");  
                        String assignVal = "UPDATE tblassessment SET totalItems = ?, assessmentDate = ?, assessmentNum = ? WHERE totalItems IS NULL AND assessmentDate IS NULL AND assessmentNum IS NULL ";
                        PreparedStatement exeSQL;
                          try {
                              exeSQL = conn.prepareStatement(assignVal);
                            exeSQL.setString(1, getTotal);
                            exeSQL.setString(2, dateVal);
                            exeSQL.setString(3, quizNum);
                            
                            exeSQL.executeUpdate();
                                JOptionPane.showMessageDialog(null, "New quiz added!");
                                
                          } catch (SQLException ex) {
                              Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
                          }

                    }
            } catch (SQLException ex) {
                Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
            }



        }
          
public void getScores(){
    DefaultTableModel TableVal = (DefaultTableModel) gradingSheet.getModel();    
    
    String aNum = AssNum.getText();
        try {
            PreparedStatement getRows = conn.prepareStatement("SELECT * FROM tblassessment ORDER BY assessment_id DESC LIMIT 1");
                ResultSet getLastRow = getRows.executeQuery();
            if(getLastRow.next()){
               int lastVal = getLastRow.getInt("assessment_id");
                System.out.println("last row value: "+lastVal);
          
               PreparedStatement ttlItems = conn.prepareStatement("SELECT totalItems, assessment_id FROM tblassessment WHERE assessment_id = ?");
                    ttlItems.setInt(1, lastVal);
                    ResultSet getTI = ttlItems.executeQuery();
                if(getTI.next()){
                    String getItems = getTI.getString("totalItems");
                    int itemVal = Integer.parseInt(getItems);
                        System.out.println("Total items: " +itemVal);
        
        try {        
        PreparedStatement applySQL = conn.prepareStatement("INSERT INTO tblScores(assessmentID, studLRN, score,studNAME) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE score = VALUES(score);"); 
        for (int rowIndex = 0; rowIndex < TableVal.getRowCount(); rowIndex++) {
            int score = (int) TableVal.getValueAt(rowIndex, 2);
                System.out.println("Student's score: "+score);
            String lrn = (String) TableVal.getValueAt(rowIndex, 0);
                System.out.println("Student's LRN: "+lrn);
            String name = (String) TableVal.getValueAt(rowIndex, 1);
                System.out.println("Student's NAME: "+name);
                                
            if(score <= itemVal && score >= 0){
                applySQL.setInt(1, lastVal);
                applySQL.setString(2, lrn);
                applySQL.setInt(3, score);
                applySQL.setString(4, name);
                    applySQL.addBatch();
                    applySQL.executeBatch(); 
                    JOptionPane.showMessageDialog(null,"The score of "+name+" has been set successfully!");
            }else{    
                JOptionPane.showMessageDialog(null,"The score of "+name+" exceeds the total number of items: "+itemVal);
            }    
            
        }
        
        
             
    }
            catch (SQLException ex) {
        Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Error updating information: " + ex.getMessage());
    }
                }
            }
    } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    
public void getStudName(){
        try {
System.out.println("Running");

String secVal = sec.getText();
String subVal = sub.getText();
String AID = (String) ANUM.getSelectedItem();
System.out.println(secVal + "\n" +subVal);
PreparedStatement assessmentVal = conn.prepareStatement("SELECT assessmentType, assessmentNum, className, subjectName, assessment_id FROM tblassessment WHERE assessment_id = ? ");

assessmentVal.setString(1,AID);


ResultSet findVal = assessmentVal.executeQuery();
if(findVal.next()){
String aType = findVal.getString("assessmentType");
String aNum = findVal.getString("assessmentNum");



System.out.println(aNum);

}
        } catch (SQLException ex) {
            Logger.getLogger(TCHLASTPAGE.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                }
        
public void getStudVal(){
          String secVal = sec.getText();
          String subVal = sub.getText();
              String assessmentType = (String) ATYPE.getSelectedItem();
    String assessmentNum = (String) ANUM.getSelectedItem();
          System.out.println("I HAVE FOUND THE SECTION: "+secVal);
          
         
          
        try {
            PreparedStatement getRows = conn.prepareStatement("SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ? AND assessmentNum = ?");
                getRows.setString(1, secVal);
                getRows.setString(2,subVal);
                getRows.setString(3,assessmentType);
                getRows.setString(4, assessmentNum);
                 ResultSet getLastRow = getRows.executeQuery();
            if(getLastRow.next()){
               int lastVal = getLastRow.getInt("assessment_id");
                System.out.println("last row value: "+lastVal);
            
            
        PreparedStatement pstmt = conn.prepareStatement("SELECT LRN, NAME, Section_Assigned FROM sf1_db WHERE Section_Assigned = ?");
pstmt.setString(1, secVal);
ResultSet getValues = pstmt.executeQuery();
ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
int q = getColVal.getColumnCount();
DefaultTableModel secAssign = (DefaultTableModel) gradingSheet.getModel();
Map<String, Integer> scores = new LinkedHashMap<>();

PreparedStatement totalItems = conn.prepareStatement("SELECT totalItems FROM tblassessment WHERE assessment_id = ?");
        totalItems.setInt(1,lastVal);
ResultSet totalItemsResult = totalItems.executeQuery();
    if(totalItemsResult.next()){
            String totalVal = totalItemsResult.getString("totalItems");
PreparedStatement scorePstmt = conn.prepareStatement("SELECT studLRN, SCORE FROM tblscores WHERE assessmentID = ? ");
    scorePstmt.setInt(1,lastVal);
ResultSet scoreResultSet = scorePstmt.executeQuery();

while (scoreResultSet.next()) {
    String lrn = scoreResultSet.getString("studLRN");
    int score = scoreResultSet.getInt("SCORE");
    scores.put(lrn, score); // Store score with LRN as the key
}


secAssign.setRowCount(0);
while (getValues.next()) {
    String LRN = getValues.getString("LRN");
    String name = getValues.getString("NAME");
    
    // Get the score from the map using LRN
    Integer score = scores.get(LRN); // This will return null if LRN is not found in scores

    // Create a new row with LRN, NAME, and SCORE
    Object[] row = new Object[4]; // Adjust the size to 3 for LRN, NAME, and SCORE
    row[0] = LRN;
    row[1] = name;
    row[2] = (score != null) ? score : "No Score Found"; // Handle case where score is not found
    row[3] = totalVal;
    secAssign.addRow(row); // Add the row to the table model
}

// Clean up resources
getValues.close();
scoreResultSet.close();
pstmt.close();
scorePstmt.close();
            
}
            }    
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

public void addTotalItems(){
          String secVal = sec.getText();
          String subVal = sub.getText();
              String assessmentType = (String) ATYPE.getSelectedItem();
    String assessmentNum = (String) ANUM.getSelectedItem();
          System.out.println("I HAVE FOUND THE SECTION: "+secVal);
          
         
          
        try {
            PreparedStatement getRows = conn.prepareStatement("SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ? AND assessmentNum = ?");
                getRows.setString(1, secVal);
                getRows.setString(2,subVal);
                getRows.setString(3,assessmentType);
                getRows.setString(4, assessmentNum);
                 ResultSet getLastRow = getRows.executeQuery();
            if(getLastRow.next()){
               int lastVal = getLastRow.getInt("assessment_id");
                System.out.println("last row value: "+lastVal);
            
            
        PreparedStatement pstmt = conn.prepareStatement("SELECT LRN, NAME, Section_Assigned FROM sf1_db WHERE Section_Assigned = ?");
pstmt.setString(1, secVal);
ResultSet getValues = pstmt.executeQuery();
ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
int q = getColVal.getColumnCount();
DefaultTableModel secAssign = (DefaultTableModel) gradingSheet.getModel();
Map<String, Integer> scores = new LinkedHashMap<>();

PreparedStatement totalItems = conn.prepareStatement("SELECT totalItems FROM tblassessment WHERE assessment_id = ?");
        totalItems.setInt(1,lastVal);
ResultSet totalItemsResult = totalItems.executeQuery();
    if(totalItemsResult.next()){
            String totalVal = totalItemsResult.getString("totalItems");
            
while (getValues.next()) {
    String LRN = getValues.getString("LRN");
    String name = getValues.getString("NAME");        
    Integer score = scores.get(LRN); 
    Object[] row = new Object[1]; 
    row[3] = totalVal;
    secAssign.addRow(row); 
}

getValues.close();

            
}
            }    
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
/*public void getGrades(){
    String secVal = sec.getText();
    String subVal = sub.getText();
    String assessmentType = (String) ATYPE.getSelectedItem();
    String assessmentNum = (String) ANUM.getSelectedItem();
    
        PreparedStatement getStud = conn.prepareStatement("SELECT score FROM tblscores WHERE ");
}                
    


    /**
     * @param args the command line arguments
     */

 public static void launch(String secVal, String subVal) {
        TCHLASTPAGE tlp = new TCHLASTPAGE(secVal, subVal);
         // Set the sub value if needed
        tlp.setVisible(true);
    }
 
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHLASTPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHLASTPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHLASTPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHLASTPAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("Default Sec Value","Default Sub Value");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ANUM;
    private javax.swing.JComboBox<String> ATYPE;
    private javax.swing.JLabel AssNum;
    public javax.swing.JLabel AssType;
    public javax.swing.JLabel adminTitle;
    private javax.swing.JLabel assType;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTable gradingSheet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> month;
    public javax.swing.JLabel sec;
    public javax.swing.JLabel sub;
    public javax.swing.JLabel tcVal;
    private javax.swing.JTextField totalitems;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
