package EvalueNetPackage;


import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aicel
 */
public class TCHSECTION extends javax.swing.JFrame {

    /**
     * Creates new form TCHSECTION
     */
    public TCHSECTION(String tcName) {
        initComponents();
        
        tcLabel.setText(tcName);
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        sectionVal.addElement("Please select a section:");
         subjectVal.addElement("Please select a subject:");
        
        getSection();
        getHE();
        getABM();
        getGAS();
        
       
    }
    
    Connection conn;
    DefaultComboBoxModel<String> sectionVal = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> subjectVal = new DefaultComboBoxModel<>();
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subCB = new javax.swing.JComboBox<>();
        secCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tcLabel = new javax.swing.JLabel();
        adminTitle = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        subject = new javax.swing.JLabel();
        section = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        subCB.setBackground(new java.awt.Color(204, 255, 204));
        subCB.setEditable(true);
        subCB.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        subCB.setModel(subjectVal);
        subCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCBActionPerformed(evt);
            }
        });
        getContentPane().add(subCB);
        subCB.setBounds(740, 250, 310, 100);

        secCB.setBackground(new java.awt.Color(204, 255, 204));
        secCB.setEditable(false);
        secCB.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        secCB.setModel(sectionVal);
        secCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCBActionPerformed(evt);
            }
        });
        getContentPane().add(secCB);
        secCB.setBounds(230, 250, 310, 100);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1150, 530, 110, 40);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1030, 530, 110, 40);

        tcLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        tcLabel.setText("TeacherName");
        getContentPane().add(tcLabel);
        tcLabel.setBounds(260, 60, 450, 20);

        adminTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle.setText("Welcome,");
        getContentPane().add(adminTitle);
        adminTitle.setBounds(170, 60, 90, 20);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton3.setText("LOG OUT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(1100, 50, 110, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Select Class:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 150, 230, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1290, 810);

        subject.setText("jLabel5");
        getContentPane().add(subject);
        subject.setBounds(1090, 10, 37, 16);

        section.setText("jLabel5");
        getContentPane().add(section);
        section.setBounds(1020, 10, 37, 16);

        setSize(new java.awt.Dimension(1294, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void subCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subCBActionPerformed

    private void secCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCBActionPerformed
        getSubs();
    }//GEN-LAST:event_secCBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String secVal =(String) secCB.getSelectedItem();
        String subVal =(String) subCB.getSelectedItem();
        
        if(secCB.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(null,"Please select a section first.");
        }else{
            TCHLASTPAGE tlp = new TCHLASTPAGE(secVal,subVal);
            tlp.setVisible(true);
            this.setVisible(false);
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = tcLabel.getText();
        TCHLANDING tl = new TCHLANDING(name);
            
               
                    tl.setVisible(true);
                        this.setVisible(false);
           
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
        dispose();
        l1.setVisible(true);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        
    }//GEN-LAST:event_formWindowActivated

public void insertVal(){
    String Sec =(String) secCB.getSelectedItem();
        String Sub =(String) subCB.getSelectedItem();
        
        String insertSecSub = "INSERT INTO tblassessment(className, subjectName) VALUES(?,?)";
        
        try {
            PreparedStatement applyIns = conn.prepareStatement(insertSecSub);
                applyIns.setString(1,Sec);
                applyIns.setString(2,Sub);
            applyIns.executeUpdate();
            System.out.println("Section: "+Sec+" and "+"Subject: "+Sub);
               
            
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    
        public void getSection(){
            String TchName = tcLabel.getText();



    try{
        Set<String> uniqueSections = new HashSet<>(); // Create a set to store unique sections
      
                
                PreparedStatement getICTSec = conn.prepareStatement("SELECT SecAssigned FROM ictsubjects WHERE TeacherAssigned = ?");
                getICTSec.setString(1, TchName);
                ResultSet findICTSec = getICTSec.executeQuery();

                while (findICTSec.next()) {
                    String getSecs = findICTSec.getString("SecAssigned");
                        
                       uniqueSections.add(getSecs);
                    System.out.println("Found section: " + getSecs);     
        }
                
          for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
                

       

        
    } catch (SQLException ex) {
        Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    

    
    
}
        
        public void getHE(){
            String TchName = tcLabel.getText(); 
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getHESec = conn.prepareStatement("SELECT SecAssigned FROM hesubjects WHERE TeacherAssigned = ?");
            getHESec.setString(1, TchName);
            ResultSet findHESec = getHESec.executeQuery();
            
            while (findHESec.next()) {
                String getSecs = findHESec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        public void getABM(){
             String TchName = tcLabel.getText();
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getSec = conn.prepareStatement("SELECT SecAssigned FROM abmsubjects WHERE TeacherAssigned = ?");
            getSec.setString(1, TchName);
            ResultSet findSec = getSec.executeQuery();
            
            while (findSec.next()) {
                String getSecs = findSec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        public void getGAS(){
             String TchName = tcLabel.getText();
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getSec = conn.prepareStatement("SELECT SecAssigned FROM gassubjects WHERE TeacherAssigned = ?");
            getSec.setString(1, TchName);
            ResultSet findSec = getSec.executeQuery();
            
            while (findSec.next()) {
                String getSecs = findSec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
   public void getSubs(){
        try {
            String TchName = tcLabel.getText();
            String getSecs = (String) secCB.getSelectedItem();
            
            PreparedStatement DBName = conn.prepareStatement("SELECT * FROM classlist WHERE Class_Name = ?");
                DBName.setString(1,getSecs);
                    ResultSet getDBName = DBName.executeQuery();
                        if(getDBName.next()){
                            String getStrand = getDBName.getString("STRAND");
                            String TblName = getStrand+"SUBJECTS";    
                            String ictSub = "SELECT SubjectName FROM "+TblName+" WHERE TeacherAssigned = ? AND SecAssigned = ?";
                            PreparedStatement getSub = conn.prepareStatement(ictSub);
                                getSub.setString(1, TchName);
                                getSub.setString(2, getSecs);
                            ResultSet findSub = getSub.executeQuery();
                                Set<String> uniqueSubjects = new HashSet<>();
                                    while (findSub.next()) {
                                String getSubs = findSub.getString("SubjectName");
                
                                 uniqueSubjects.add(getSubs);
                                System.out.println("Found subject: " + getSubs);
                                }
            
            // Add unique subjects to subjectVal
            subjectVal.removeAllElements(); // Clear existing elements
            for (String subject : uniqueSubjects) {
                subjectVal.addElement(subject);
                
            }
                        }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
   
   }
        
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    /**
     * @param args the command line arguments
     */
    
     public static void launch(String tchVal) {
        TCHSECTION ts = new TCHSECTION(tchVal);
         // Set the sub value if needed
        ts.setVisible(true);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHSECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHSECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHSECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHSECTION.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminTitle;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JComboBox<String> secCB;
    public javax.swing.JLabel section;
    public javax.swing.JComboBox<String> subCB;
    public javax.swing.JLabel subject;
    public javax.swing.JLabel tcLabel;
    // End of variables declaration//GEN-END:variables
}
