/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EvalueNetPackage;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author lordz
 */
public class TCHSUMMARY extends javax.swing.JFrame {

    /**
     * Creates new form TCHSUMMARY
     */
    public TCHSUMMARY(String value) {
        initComponents();
        tcLabel.setText(value);
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(TCHSUMMARY.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TCHSUMMARY.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        getSection();
        getHE();
        getABM();
        getGAS();
    }
    
    Connection conn;
    DefaultComboBoxModel<String> sectionVal = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> subjectVal = new DefaultComboBoxModel<>();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secCB = new javax.swing.JComboBox<>();
        subCB = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        adminTitle = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        secCB.setBackground(new java.awt.Color(204, 255, 204));
        secCB.setEditable(false);
        secCB.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        secCB.setModel(sectionVal);
        secCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secCBActionPerformed(evt);
            }
        });

        subCB.setBackground(new java.awt.Color(204, 255, 204));
        subCB.setEditable(true);
        subCB.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        subCB.setModel(subjectVal);
        subCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCBActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        adminTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle.setText("Welcome,");

        tcLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        tcLabel.setText("Maria Aurea Reyes Jabon");

        jButton1.setText("For Advisory Class");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(adminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secCB, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subCB, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(462, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(secCB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subCB, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(418, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secCBActionPerformed
        getSubs();
    }//GEN-LAST:event_secCBActionPerformed

    private void subCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subCBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Sec =(String) secCB.getSelectedItem();
        String Sub =(String) subCB.getSelectedItem();
        String tc = tcLabel.getText();

        SECTIONSOG ta = new SECTIONSOG(Sec,Sub,tc);
        ta.setVisible(true);
        this.setVisible(false);
        

        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        checkAdvisory();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String name = tcLabel.getText();
        TCHLANDING tl = new TCHLANDING(name);       
        tl.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void checkAdvisory(){
        
        
        String adviserName = tcLabel.getText();
        
        try {
            PreparedStatement checkAdv = conn.prepareStatement("SELECT * FROM classlist WHERE Adviser_Name = ?");
               checkAdv.setString(1,adviserName);
                    ResultSet hasAdviser = checkAdv.executeQuery();
                        if(hasAdviser.next()){
                            String section = hasAdviser.getString("Class_Name");
                            String strand = hasAdviser.getString("STRAND");
                            
                               JOptionPane.showMessageDialog(null,"The advisory of: "+adviserName+" is "+strand+"-"+section);
                                String name = tcLabel.getText();    
                               
                               TCHADVISORY tl = new TCHADVISORY(tcLabel.getText(),strand,section);

        
        tl.setVisible(true);
        this.setVisible(false);

                        
                        }else{
                            JOptionPane.showMessageDialog(null,"You have no advisory class");
                        }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSUMMARY.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    
    public void getSection(){
            String TchName = tcLabel.getText();



    try{
        Set<String> uniqueSections = new HashSet<>(); // Create a set to store unique sections
      
                
                PreparedStatement getICTSec = conn.prepareStatement("SELECT SecAssigned FROM ictsubjects WHERE TeacherAssigned = ?");
                getICTSec.setString(1, TchName);
                ResultSet findICTSec = getICTSec.executeQuery();

                while (findICTSec.next()) {
                    String getSecs = findICTSec.getString("SecAssigned");
                        
                       uniqueSections.add(getSecs);
                    System.out.println("Found section: " + getSecs);     
        }
                
          for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
                

       

        
    } catch (SQLException ex) {
        Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    

    
    
}
        
        public void getHE(){
            String TchName = tcLabel.getText(); 
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getHESec = conn.prepareStatement("SELECT SecAssigned FROM hesubjects WHERE TeacherAssigned = ?");
            getHESec.setString(1, TchName);
            ResultSet findHESec = getHESec.executeQuery();
            
            while (findHESec.next()) {
                String getSecs = findHESec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        public void getABM(){
             String TchName = tcLabel.getText();
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getSec = conn.prepareStatement("SELECT SecAssigned FROM abmsubjects WHERE TeacherAssigned = ?");
            getSec.setString(1, TchName);
            ResultSet findSec = getSec.executeQuery();
            
            while (findSec.next()) {
                String getSecs = findSec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
        public void getGAS(){
             String TchName = tcLabel.getText();
            
        try {
            Set<String> uniqueSections = new HashSet<>();
            
            PreparedStatement getSec = conn.prepareStatement("SELECT SecAssigned FROM gassubjects WHERE TeacherAssigned = ?");
            getSec.setString(1, TchName);
            ResultSet findSec = getSec.executeQuery();
            
            while (findSec.next()) {
                String getSecs = findSec.getString("SecAssigned");
                
                uniqueSections.add(getSecs);
                System.out.println("Found section: " + getSecs);
            }
            
            
            // Add unique sections to sectionVal
            //  // Clear existing elements
            
            for (String section : uniqueSections) {
                sectionVal.addElement(section);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
   public void getSubs(){
        try {
            String TchName = tcLabel.getText();
            String getSecs = (String) secCB.getSelectedItem();
            
            String ictSub = "SELECT SubjectName FROM ictsubjects WHERE TeacherAssigned = ? AND SecAssigned = ?";
            PreparedStatement getSub = conn.prepareStatement(ictSub);
            getSub.setString(1, TchName);
            getSub.setString(2, getSecs);
            ResultSet findSub = getSub.executeQuery();
            Set<String> uniqueSubjects = new HashSet<>();
            while (findSub.next()) {
                String getSubs = findSub.getString("SubjectName");
                
                uniqueSubjects.add(getSubs);
                System.out.println("Found subject: " + getSubs);
            }
            
            // Add unique subjects to subjectVal
            subjectVal.removeAllElements(); // Clear existing elements
            for (String subject : uniqueSubjects) {
                subjectVal.addElement(subject);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(TCHSECTION.class.getName()).log(Level.SEVERE, null, ex);
        }
   
   }
        
   
        
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    public static void launch(String tchVal) {
        TCHSUMMARY tl = new TCHSUMMARY(tchVal);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHSUMMARY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHSUMMARY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHSUMMARY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHSUMMARY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<String> secCB;
    public javax.swing.JComboBox<String> subCB;
    public javax.swing.JLabel tcLabel;
    // End of variables declaration//GEN-END:variables
}
