/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.admin;

import com.evaluenet.login.LoginUI;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import com.evaluenet.login.LoginUI;
/**
 *
 * @author lordz
 */
public class SchoolForm1 extends javax.swing.JFrame {

    /**
     * Creates new form SchoolForm1
     */
    public SchoolForm1(String val) {
        initComponents();
            adminTtl.setText(val);
            
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(SchoolForm1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SchoolForm1.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
          
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    Connection conn;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        motherTongue = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ethnicGroup = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        religion = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mName = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        LModality = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        LRN = new javax.swing.JTextField();
        year = new javax.swing.JComboBox<>();
        sex = new javax.swing.JComboBox<>();
        age = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        month = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        SPECinfo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        adminTitle1 = new javax.swing.JLabel();
        adminTtl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 560));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel1.setText("Student LRN: ");
        jLabel1.setToolTipText("");
        jLabel1.setAutoscrolls(true);
        jLabel1.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 240, 90, 30);

        Name.setForeground(new java.awt.Color(51, 51, 51));
        Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFocusLost(evt);
            }
        });
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NameKeyTyped(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(330, 290, 230, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setToolTipText("");
        jLabel2.setAutoscrolls(true);
        jLabel2.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel2.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 290, 40, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Sex:");
        jLabel3.setToolTipText("");
        jLabel3.setAutoscrolls(true);
        jLabel3.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 330, 30, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setText("Birthday:");
        jLabel14.setToolTipText("");
        jLabel14.setAutoscrolls(true);
        jLabel14.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel14.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel14.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(270, 380, 60, 40);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setText("Age:");
        jLabel15.setToolTipText("");
        jLabel15.setAutoscrolls(true);
        jLabel15.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel15.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel15.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 440, 40, 30);

        motherTongue.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                motherTongueFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                motherTongueFocusLost(evt);
            }
        });
        motherTongue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherTongueActionPerformed(evt);
            }
        });
        motherTongue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                motherTongueKeyPressed(evt);
            }
        });
        getContentPane().add(motherTongue);
        motherTongue.setBounds(330, 490, 230, 30);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setText("Mother Tongue:");
        jLabel16.setToolTipText("");
        jLabel16.setAutoscrolls(true);
        jLabel16.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel16.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel16.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 490, 130, 30);

        ethnicGroup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ethnicGroupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ethnicGroupFocusLost(evt);
            }
        });
        ethnicGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ethnicGroupActionPerformed(evt);
            }
        });
        ethnicGroup.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ethnicGroupKeyPressed(evt);
            }
        });
        getContentPane().add(ethnicGroup);
        ethnicGroup.setBounds(330, 540, 230, 30);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setText("Ethnic Group:");
        jLabel17.setToolTipText("");
        jLabel17.setAutoscrolls(true);
        jLabel17.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel17.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel17.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(240, 540, 100, 30);

        religion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                religionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                religionFocusLost(evt);
            }
        });
        religion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                religionActionPerformed(evt);
            }
        });
        religion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                religionKeyPressed(evt);
            }
        });
        getContentPane().add(religion);
        religion.setBounds(800, 240, 230, 30);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel18.setText("Religion:");
        jLabel18.setToolTipText("");
        jLabel18.setAutoscrolls(true);
        jLabel18.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel18.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel18.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(740, 240, 60, 30);

        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        getContentPane().add(address);
        address.setBounds(800, 290, 230, 30);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel19.setText("Address:");
        jLabel19.setToolTipText("");
        jLabel19.setAutoscrolls(true);
        jLabel19.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel19.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel19.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(740, 290, 80, 30);

        fName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fNameFocusLost(evt);
            }
        });
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        fName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fNameKeyTyped(evt);
            }
        });
        getContentPane().add(fName);
        fName.setBounds(800, 340, 230, 30);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel20.setText("Father's Name:");
        jLabel20.setToolTipText("");
        jLabel20.setAutoscrolls(true);
        jLabel20.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel20.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel20.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(700, 340, 100, 30);

        mName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mNameFocusLost(evt);
            }
        });
        mName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNameActionPerformed(evt);
            }
        });
        mName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mNameKeyTyped(evt);
            }
        });
        getContentPane().add(mName);
        mName.setBounds(800, 390, 230, 30);

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel21.setText("Mother's Name: ");
        jLabel21.setToolTipText("");
        jLabel21.setAutoscrolls(true);
        jLabel21.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel21.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel21.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(690, 390, 110, 30);

        Contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContactFocusLost(evt);
            }
        });
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        Contact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContactKeyTyped(evt);
            }
        });
        getContentPane().add(Contact);
        Contact.setBounds(800, 440, 230, 30);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel22.setText("Contact Number of Parent: ");
        jLabel22.setToolTipText("");
        jLabel22.setAutoscrolls(true);
        jLabel22.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel22.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel22.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(630, 440, 170, 30);

        LModality.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LModalityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LModalityFocusLost(evt);
            }
        });
        LModality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LModalityActionPerformed(evt);
            }
        });
        getContentPane().add(LModality);
        LModality.setBounds(800, 490, 230, 30);

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel23.setText("Learning Modality:");
        jLabel23.setToolTipText("");
        jLabel23.setAutoscrolls(true);
        jLabel23.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel23.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel23.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(680, 490, 120, 30);

        LRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        LRN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LRNFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LRNFocusLost(evt);
            }
        });
        LRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LRNActionPerformed(evt);
            }
        });
        LRN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LRNKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LRNKeyTyped(evt);
            }
        });
        getContentPane().add(LRN);
        LRN.setBounds(330, 240, 230, 30);

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015" ,"2016","2017","2018","2019","2020","2021","2022","2023","2024"}));
        year.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                yearFocusLost(evt);
            }
        });
        year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearKeyPressed(evt);
            }
        });
        getContentPane().add(year);
        year.setBounds(520, 390, 72, 25);

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male","Female" }));
        sex.setMinimumSize(new java.awt.Dimension(72, 20));
        sex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sexFocusLost(evt);
            }
        });
        sex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sexKeyPressed(evt);
            }
        });
        getContentPane().add(sex);
        sex.setBounds(330, 340, 90, 25);

        age.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60" }));
        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });
        age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageKeyPressed(evt);
            }
        });
        getContentPane().add(age);
        age.setBounds(330, 440, 90, 25);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31" }));
        day.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dayFocusLost(evt);
            }
        });
        day.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dayKeyPressed(evt);
            }
        });
        getContentPane().add(day);
        day.setBounds(430, 390, 72, 25);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 51));
        jLabel4.setText("Student Information");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 140, 390, 50);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 590, 170, 50);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12"}));
        month.setMinimumSize(new java.awt.Dimension(72, 20));
        month.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthFocusLost(evt);
            }
        });
        month.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                monthKeyPressed(evt);
            }
        });
        getContentPane().add(month);
        month.setBounds(330, 390, 90, 25);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setText("Year");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 370, 37, 14);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel6.setText("Month");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 370, 28, 14);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setText("Day");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 370, 37, 14);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(870, 590, 170, 50);

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel24.setText("Specialization:");
        jLabel24.setToolTipText("");
        jLabel24.setAutoscrolls(true);
        jLabel24.setMaximumSize(new java.awt.Dimension(76, 16));
        jLabel24.setMinimumSize(new java.awt.Dimension(76, 16));
        jLabel24.setPreferredSize(new java.awt.Dimension(130, 16));
        getContentPane().add(jLabel24);
        jLabel24.setBounds(710, 540, 90, 30);

        SPECinfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","ICT","HE","GAS","ABM" }));
        SPECinfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SPECinfoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SPECinfoFocusLost(evt);
            }
        });
        getContentPane().add(SPECinfo);
        SPECinfo.setBounds(800, 540, 72, 25);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("LOG OUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1100, 50, 110, 40);

        adminTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle1.setText("Welcome,");
        getContentPane().add(adminTitle1);
        adminTitle1.setBounds(160, 50, 90, 20);

        adminTtl.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTtl.setText("Admin!");
        getContentPane().add(adminTtl);
        adminTtl.setBounds(250, 50, 120, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1296, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void motherTongueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherTongueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherTongueActionPerformed

    private void ethnicGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ethnicGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ethnicGroupActionPerformed

    private void religionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_religionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void mNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mNameActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void LModalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LModalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LModalityActionPerformed

    private void LRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LRNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(LRN.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            LRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));            
        }else if(Name.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(motherTongue.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            motherTongue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(ethnicGroup.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            ethnicGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(religion.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(address.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(fName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            fName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(mName.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            mName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(Contact.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else if(LModality.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please fill out the field.");
            LModality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,0,0)));
        }else{
            try {
                String Month = (String) month.getSelectedItem();
                String Day = (String) day.getSelectedItem();
                String Year = (String) year.getSelectedItem();
                
                String Birthday = Month + "-" + Day + "-" + Year;
                
                String studInfo[] = {
                    LRN.getText(), //0
                    Name.getText(), //1
                    (String) sex.getSelectedItem(), //2
                    (String) age.getSelectedItem(), //3
                    motherTongue.getText(), //4
                    ethnicGroup.getText(), //5
                    religion.getText(), //6
                    address.getText(), //7
                    fName.getText(), //8
                    mName.getText(), //9
                    Contact.getText(), //10
                    LModality.getText(), //11
                    (String) SPECinfo.getSelectedItem()
                };
                
                String sqlQuery = "INSERT INTO sf1_db(LRN,NAME,SEX,BIRTHDAY, AGE,MOTHER_TONGUE, ETHNIC_GROUP, RELIGION, ADDRESS, FATHER_NAME, MOTHER_NAME, CONTACT_NUMBER, LEARNING_MODALITY, STRAND) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pstm = conn.prepareStatement(sqlQuery);
                pstm.setString(1, studInfo[0]);
                pstm.setString(2, studInfo[1]);
                pstm.setString(3, studInfo[2]);
                pstm.setString(4, Birthday);
                pstm.setString(5, studInfo[3]);
                pstm.setString(6, studInfo[4]);
                pstm.setString(7, studInfo[5]);
                pstm.setString(8, studInfo[6]);
                pstm.setString(9, studInfo[7]);
                pstm.setString(10, studInfo[8]);
                pstm.setString(11, studInfo[9]);
                pstm.setString(12, studInfo[10]);
                pstm.setString(13, studInfo[11]);
                pstm.setString(14, studInfo[12]);
               
                
                
                
                      
                      String cnVal = Contact.getText().trim();
                      String lrnVal = LRN.getText().trim();
                      int cnCharCount = cnVal.length();
                      int lrnCharCount = lrnVal.length();
                      if(cnCharCount == 11 && lrnCharCount == 12){
                            
                        pstm.executeUpdate();
                        JOptionPane.showMessageDialog(null,"New Sudent added!");
                            
                            LRN.setText("");
                    Name.setText("");
                    motherTongue.setText("");
                    ethnicGroup.setText("");
                    religion.setText("");
                    address.setText("");
                    fName.setText("");
                    mName.setText("");
                    Contact.setText("");
                    LModality.setText("");
                    
                            
                      }else if(cnCharCount > 11 || cnCharCount < 11 ){
                          JOptionPane.showMessageDialog(null,"Your Contact number must be 11 characters.");
                      }else if(lrnCharCount > 12 || lrnCharCount < 12 ){
                          JOptionPane.showMessageDialog(null,"Your LRN number must be 12 characters.");
                      }
                  else{
                      
                  }
                

            } catch (SQLException ex) {
                Logger.getLogger(SchoolForm1.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error creating new student: " + ex.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    private void LRNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LRNKeyTyped
      char c = evt.getKeyChar();
      if(!Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_LRNKeyTyped

    private void ContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactKeyTyped
        char c = evt.getKeyChar();
      if(!Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_ContactKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        StudentAdd sa = new StudentAdd(adminTtl.getText());
        sa.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LRNFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LRNFocusGained
        LRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_LRNFocusGained

    private void LRNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LRNFocusLost
        LRN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_LRNFocusLost

    private void NameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFocusGained
        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_NameFocusGained

    private void NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFocusLost
         Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_NameFocusLost

    private void sexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sexFocusGained
        sex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_sexFocusGained

    private void sexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sexFocusLost
        sex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_sexFocusLost

    private void monthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFocusGained
        month.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_monthFocusGained

    private void monthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFocusLost
        // TODO add your handling code here:
        month.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_monthFocusLost

    private void dayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayFocusGained
        day.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_dayFocusGained

    private void dayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dayFocusLost
        // TODO add your handling code here:
        day.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204,204,204)));
    }//GEN-LAST:event_dayFocusLost

    private void yearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearFocusGained
        // TODO add your handling code here:
        year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_yearFocusGained

    private void yearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearFocusLost
        // TODO add your handling code here:
        year.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_yearFocusLost

    private void ageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusGained
        // TODO add your handling code here:
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_ageFocusGained

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
        // TODO add your handling code here:
        age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_ageFocusLost

    private void motherTongueFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherTongueFocusGained
        // TODO add your handling code here:
        motherTongue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_motherTongueFocusGained

    private void motherTongueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_motherTongueFocusLost
        // TODO add your handling code here:
        motherTongue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_motherTongueFocusLost

    private void ethnicGroupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ethnicGroupFocusGained
        // TODO add your handling code here:
        ethnicGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_ethnicGroupFocusGained

    private void ethnicGroupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ethnicGroupFocusLost
        // TODO add your handling code here:
        ethnicGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_ethnicGroupFocusLost

    private void religionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_religionFocusGained
        // TODO add your handling code here:
        religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_religionFocusGained

    private void religionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_religionFocusLost
        // TODO add your handling code here:
        religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_religionFocusLost

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_addressFocusLost

    private void fNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFocusGained
        // TODO add your handling code here:
        fName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_fNameFocusGained

    private void fNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fNameFocusLost
        // TODO add your handling code here:
        fName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_fNameFocusLost

    private void mNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mNameFocusGained
        // TODO add your handling code here:
        mName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_mNameFocusGained

    private void mNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mNameFocusLost
        // TODO add your handling code here:
        mName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_mNameFocusLost

    private void ContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactFocusGained
        // TODO add your handling code here:
        Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_ContactFocusGained

    private void ContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactFocusLost
        // TODO add your handling code here:
        Contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_ContactFocusLost

    private void LModalityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LModalityFocusGained
        // TODO add your handling code here:
        LModality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,102,51)));
    }//GEN-LAST:event_LModalityFocusGained

    private void LModalityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LModalityFocusLost
        // TODO add your handling code here:
        LModality.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
    }//GEN-LAST:event_LModalityFocusLost

    private void SPECinfoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SPECinfoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECinfoFocusGained

    private void SPECinfoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SPECinfoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_SPECinfoFocusLost

    private void LRNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LRNKeyPressed
     if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        Name.requestFocusInWindow();
     }   
    }//GEN-LAST:event_LRNKeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LoginUI l1 = new LoginUI();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            dispose();
            l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sexKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sexKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        month.requestFocusInWindow();
     }
    }//GEN-LAST:event_sexKeyPressed

    private void NameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        sex.requestFocusInWindow();
     }
    }//GEN-LAST:event_NameKeyPressed

    private void monthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monthKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        day.requestFocusInWindow();
     }
    }//GEN-LAST:event_monthKeyPressed

    private void dayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dayKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        year.requestFocusInWindow();
     }
    }//GEN-LAST:event_dayKeyPressed

    private void yearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        age.requestFocusInWindow();
     }
    }//GEN-LAST:event_yearKeyPressed

    private void ageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        motherTongue.requestFocusInWindow();
     }
    }//GEN-LAST:event_ageKeyPressed

    private void ethnicGroupKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ethnicGroupKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        religion.requestFocusInWindow();
     }
    }//GEN-LAST:event_ethnicGroupKeyPressed

    private void motherTongueKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_motherTongueKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
        ethnicGroup.requestFocusInWindow();
     }
    }//GEN-LAST:event_motherTongueKeyPressed

    private void religionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_religionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_religionKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressKeyPressed

    private void NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameKeyTyped
        char c = evt.getKeyChar();
      if(Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_NameKeyTyped

    private void fNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameKeyTyped
         char c = evt.getKeyChar();
      if(Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_fNameKeyTyped

    private void mNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mNameKeyTyped
         char c = evt.getKeyChar();
      if(Character.isDigit(c)){
          evt.consume();
      }
    }//GEN-LAST:event_mNameKeyTyped

    /**
     * @param args the command line arguments
     */
    
    public static void launch(String TCname) {
        SchoolForm1 tl = new SchoolForm1(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField LModality;
    private javax.swing.JTextField LRN;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox<String> SPECinfo;
    private javax.swing.JTextField address;
    public javax.swing.JLabel adminTitle1;
    public javax.swing.JLabel adminTtl;
    private javax.swing.JComboBox<String> age;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField ethnicGroup;
    private javax.swing.JTextField fName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mName;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField motherTongue;
    private javax.swing.JTextField religion;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
