/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.admin;

import com.evaluenet.admin.ClassForm;
import com.evaluenet.admin.SubjectAdd;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lordz
 */
public class SubjectForm extends javax.swing.JFrame {

    /**
     * Creates new form SubjectForm
     */
    public SubjectForm(String val) {
        initComponents();
        adminName.setText(val);
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        getTeachers();
        
        java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
          
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

Connection conn;
DefaultComboBoxModel<String> secModel = new DefaultComboBoxModel<>();
DefaultComboBoxModel<String> tcModel = new DefaultComboBoxModel<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        subjectField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        strandDropdown = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        secDD = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tcDD = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        adminName = new javax.swing.JLabel();
        adminTitle1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setText("Add a Subject Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 270, 162, 21);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel2.setText("Choose a Strand:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 270, 133, 21);

        subjectField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subjectFieldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subjectFieldKeyTyped(evt);
            }
        });
        getContentPane().add(subjectField);
        subjectField.setBounds(310, 300, 178, 50);

        submitBtn.setBackground(new java.awt.Color(204, 255, 204));
        submitBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(1120, 430, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 51));
        jLabel5.setText("SUBJECT MANAGEMENT SYSTEM");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 130, 680, 54);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(960, 430, 140, 40);

        strandDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","ICT", "HE", "ABM", "GAS" }));
        strandDropdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                strandDropdownMouseClicked(evt);
            }
        });
        strandDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strandDropdownActionPerformed(evt);
            }
        });
        strandDropdown.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                strandDropdownKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                strandDropdownKeyTyped(evt);
            }
        });
        getContentPane().add(strandDropdown);
        strandDropdown.setBounds(520, 300, 143, 50);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel3.setText("Assign Section:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 270, 143, 21);

        secDD.setModel(secModel);
        secDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                secDDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                secDDKeyTyped(evt);
            }
        });
        getContentPane().add(secDD);
        secDD.setBounds(690, 300, 143, 50);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("Assign Teacher:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(860, 270, 143, 21);

        tcDD.setModel(tcModel);
        tcDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcDDActionPerformed(evt);
            }
        });
        tcDD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tcDDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcDDKeyTyped(evt);
            }
        });
        getContentPane().add(tcDD);
        tcDD.setBounds(860, 300, 143, 50);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setText("LOG OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1100, 50, 110, 40);

        adminName.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminName.setText("Admin!");
        getContentPane().add(adminName);
        adminName.setBounds(250, 50, 150, 20);

        adminTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle1.setText("Welcome,");
        getContentPane().add(adminTitle1);
        adminTitle1.setBounds(160, 50, 90, 20);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1280, 800);

        setSize(new java.awt.Dimension(1296, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        
        String strandType =(String) strandDropdown.getSelectedItem();
        if(subjectField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please enter a subject name.");
        }else if(strandType.equals("")){
            JOptionPane.showMessageDialog(null,"Please choose a strand.");
        }else{
            String subName = subjectField.getText();
            String strandName = (String) strandDropdown.getSelectedItem();
            String secName = (String) secDD.getSelectedItem();
            String tcName = (String) tcDD.getSelectedItem();
            
                    if(strandType.equals("ICT")){
                        try {
                    String sqlIct = "INSERT INTO ictsubjects(SubjectName,SecAssigned,TeacherAssigned) VALUES(?,?,?)";
                    PreparedStatement ict = conn.prepareStatement(sqlIct);
                    ict.setString(1,subName);
                    ict.setString(2, secName);
                    ict.setString(3, tcName);
                    ict.executeUpdate();
                    JOptionPane.showMessageDialog(null,"New subject successfully added!");
                } catch (SQLException ex) {
                    Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    }else if(strandType.equals("HE")){
                        try {
                            String sqlHe = "INSERT INTO hesubjects(SubjectName,SecAssigned,TeacherAssigned) VALUES(?,?,?)";
                    PreparedStatement he = conn.prepareStatement(sqlHe);
                        he.setString(1,subName);
                        he.setString(2, secName);
                        he.setString(3, tcName);
                        he.executeUpdate();
                    JOptionPane.showMessageDialog(null,"New subject successfully added!");
                } catch (SQLException ex) {
                    Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                    }else if(strandType.equals("ABM")){
                        try {
                    String sqlAbm = "INSERT INTO abmsubjects(SubjectName,SecAssigned,TeacherAssigned) VALUES(?,?,?)";
                    PreparedStatement abm = conn.prepareStatement(sqlAbm);
                    abm.setString(1,subName);
                    abm.setString(2, secName);
                    abm.setString(3, tcName);
                    abm.executeUpdate();
                    JOptionPane.showMessageDialog(null,"New subject successfully added!");
                } catch (SQLException ex) {
                    Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
                } 
                    }else if(strandType.equals("GAS")){
                        try {
                    String sqlGas = "INSERT INTO gassubjects(SubjectName,SecAssigned,TeacherAssigned) VALUES(?,?,?)";
                    PreparedStatement gas = conn.prepareStatement(sqlGas);
                    gas.setString(1,subName);
                    gas.setString(2, secName);
                    gas.setString(3, tcName);
                    gas.executeUpdate();
                    JOptionPane.showMessageDialog(null,"New subject successfully added!");
                } catch (SQLException ex) {
                    Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
                } 
                    }    
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SubjectAdd sa = new SubjectAdd(adminName.getText());
        sa.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void subjectFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectFieldKeyTyped
        
    }//GEN-LAST:event_subjectFieldKeyTyped

    private void strandDropdownKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strandDropdownKeyTyped
        
    }//GEN-LAST:event_strandDropdownKeyTyped

    private void subjectFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectFieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
            strandDropdown.requestFocusInWindow();
     }
    }//GEN-LAST:event_subjectFieldKeyPressed

    private void strandDropdownKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_strandDropdownKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){      
            submitBtn.doClick();
     }
    }//GEN-LAST:event_strandDropdownKeyPressed

    private void secDDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secDDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_secDDKeyPressed

    private void secDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_secDDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_secDDKeyTyped

    private void tcDDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcDDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcDDKeyPressed

    private void tcDDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcDDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tcDDKeyTyped

    private void strandDropdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_strandDropdownMouseClicked
        
    }//GEN-LAST:event_strandDropdownMouseClicked

    private void strandDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strandDropdownActionPerformed
        getVal();
    }//GEN-LAST:event_strandDropdownActionPerformed

    private void tcDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcDDActionPerformed
        
    }//GEN-LAST:event_tcDDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       int response = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Exit Confirmation",JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION){
                dispose();
            }
    }//GEN-LAST:event_formWindowClosing
    
    public void getTeachers() {
    String getTC = "SELECT NAME FROM tchInfo";
    try {
        PreparedStatement applySQL = conn.prepareStatement(getTC);
        ResultSet tcVal = applySQL.executeQuery();
        
        System.out.println("All Rows:");
        while(tcVal.next()) {
            
            String tcName = tcVal.getString("NAME");
            System.out.println("FullName: " + tcName);
            tcModel.addElement(tcName);
        }
        
        applySQL.executeQuery();
        
        
    } catch (SQLException ex) {
        Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    
    public void getVal(){
    String chooseStrand = (String) strandDropdown.getSelectedItem();    
            secDD.removeAllItems();
    
    if(chooseStrand.equals("ICT")){
            try {
                String ictStrand = "SELECT SctnName FROM ictsections";
                PreparedStatement getICT = conn.prepareStatement(ictStrand);
                ResultSet getSection = getICT.executeQuery();
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secModel.addElement(secVal);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("HE") ){
            try {
                String heStrand = "SELECT SctnName FROM hesections";      //Change strand
                PreparedStatement getHE = conn.prepareStatement(heStrand); //Change strand
                ResultSet getSection = getHE.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("GAS") ){
            try {
                String gasStrand = "SELECT SctnName FROM gassections";      //Change strand
                PreparedStatement getGAS = conn.prepareStatement(gasStrand); //Change strand
                ResultSet getSection = getGAS.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(chooseStrand.equals("ABM") ){
            try {
                String abmStrand = "SELECT SctnName FROM abmsections";      //Change strand
                PreparedStatement getABM = conn.prepareStatement(abmStrand); //Change strand
                ResultSet getSection = getABM.executeQuery();               //Change strand    
                    
                while(getSection.next()){
                    String secVal = getSection.getString("SctnName");
                    secModel.addElement(secVal);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ClassForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void launch(String TCname) {
        SubjectForm tl = new SubjectForm(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel adminName;
    public javax.swing.JLabel adminTitle1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> secDD;
    private javax.swing.JComboBox<String> strandDropdown;
    private javax.swing.JTextField subjectField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JComboBox<String> tcDD;
    // End of variables declaration//GEN-END:variables
}
