/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.admin;

import com.evaluenet.teacher.TCHLANDING;
import com.evaluenet.admin.Admin;
import com.evaluenet.admin.SubjectAdd;
import com.evaluenet.login.LoginUI;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author lordz
 */
public class tablesubject extends javax.swing.JFrame {

    /**
     * Creates new form tablesubject
     */
    public tablesubject(String val) {
        initComponents();
        
        adminName.setText(val);
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(tablesubject.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(tablesubject.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            java.awt.Image img = new ImageIcon(this.getClass().getResource("iconic.png")).getImage();
        this.setIconImage(img);
        subTbl.setDefaultEditor(Object.class, null);  
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        resetBtn.setEnabled(false);
                editBtn.setEnabled(false);
    }

    Connection conn;
    DefaultComboBoxModel<String> tcModel = new DefaultComboBoxModel<>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        subTbl = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        adminName = new javax.swing.JLabel();
        adminTitle1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tblFilter = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jButton4.setBackground(new java.awt.Color(0, 102, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        subTbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        subTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Section", "Teacher"
            }
        ));
        jScrollPane1.setViewportView(subTbl);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(470, 160, 750, 250);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton5.setText(" Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1110, 440, 110, 40);

        SaveBtn.setBackground(new java.awt.Color(204, 255, 204));
        SaveBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        SaveBtn.setText("Save Changes");
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(950, 440, 150, 40);

        jButton6.setBackground(new java.awt.Color(204, 255, 204));
        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton6.setText("LOG OUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(1100, 50, 110, 40);

        adminName.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminName.setText("Admin!");
        getContentPane().add(adminName);
        adminName.setBounds(250, 50, 150, 20);

        adminTitle1.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle1.setText("Welcome,");
        getContentPane().add(adminTitle1);
        adminTitle1.setBounds(160, 50, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel6.setText("Search Filter:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 190, 210, 30);

        tblFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select specialization:  ", "ICT", "HE", "GAS", "ABM" }));
        tblFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblFilterActionPerformed(evt);
            }
        });
        getContentPane().add(tblFilter);
        tblFilter.setBounds(150, 230, 140, 30);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 280, 100, 40);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn);
        resetBtn.setBounds(600, 430, 80, 30);

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        getContentPane().add(editBtn);
        editBtn.setBounds(500, 430, 80, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Admin a1 = new Admin(adminName.getText());
        a1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SubjectAdd sa = new SubjectAdd(adminName.getText());
        sa.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        LoginUI l1 = new LoginUI();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
        if(answer == JOptionPane.YES_OPTION){
            dispose();
            l1.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int response = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Exit Confirmation",JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION){
                dispose();
            }
    }//GEN-LAST:event_formWindowClosing

    private void tblFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblFilterActionPerformed
        

    }//GEN-LAST:event_tblFilterActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tblVal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        int response = JOptionPane.showConfirmDialog(this,"Are you sure you want to reset the table?","Reset Confirmation",JOptionPane.YES_NO_OPTION);
            if(response == JOptionPane.YES_OPTION){
                tblVal();
            }
        
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
          editTbl();
          JOptionPane.showMessageDialog(null,"The table is now editable");
    }//GEN-LAST:event_editBtnActionPerformed

    public void getTeachers() {
    String getTC = "SELECT FullName, username FROM tblaccounts";
    try {
        PreparedStatement applySQL = conn.prepareStatement(getTC);
        ResultSet tcVal = applySQL.executeQuery();
        
        System.out.println("All Rows:");
        while(tcVal.next()) {
            String getUN = tcVal.getString("username");
            String tcName = tcVal.getString("FullName");
            System.out.println("Username: " + getUN + ", FullName: " + tcName);
        }
        
        
        tcVal = applySQL.executeQuery();
        
        System.out.println("\nRows with 'TCH' in username:");
        while(tcVal.next()) {
            String getUN = tcVal.getString("username");
            if(getUN.contains("TCH")) {
                String tcName = tcVal.getString("FullName");
                tcModel.addElement(tcName);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(SubjectForm.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    
    public void editTbl(){
        getTeachers();
        
        JComboBox<String> comboBox = new JComboBox<>();               
            comboBox.setModel(tcModel);
            subTbl.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(comboBox));
    }
    
    
    public void tblVal(){
        String strandVal = (String) tblFilter.getSelectedItem();
        boolean isICT = strandVal.equals("ICT");
        boolean isGAS = strandVal.equals("GAS");
        boolean isHE = strandVal.equals("HE");
        boolean isABM = strandVal.equals("ABM");
            subTbl.setDefaultEditor(Object.class, null);
            if(isICT){
                getIctVal();
                    resetBtn.setEnabled(true);
                editBtn.setEnabled(true);
            }else if(isGAS){
                getGasVal();
                resetBtn.setEnabled(true);
                editBtn.setEnabled(true);
            }else if(isHE){
                getHeVal();
                resetBtn.setEnabled(true);
                editBtn.setEnabled(true);
            }else if(isABM){
                getAbmVal();
                resetBtn.setEnabled(true);
                editBtn.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null,"Please select a strand.");
                
            }
    }
    
    
     public void getIctVal(){
        
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT*FROM ictsubjects");
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) subTbl.getModel();
            
            secAssign.setRowCount(0);
            while (getValues.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = getValues.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public void getHeVal(){
        
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT*FROM hesubjects");
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) subTbl.getModel();
            
            
            secAssign.setRowCount(0);
            while (getValues.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = getValues.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public void getAbmVal(){
        
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT*FROM abmsubjects");
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) subTbl.getModel();
            
            
            secAssign.setRowCount(0);
            while (getValues.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = getValues.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public void getGasVal(){
        
        try {
            int q;
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM gassubjects");
            ResultSet getValues = pstmt.executeQuery();
            ResultSetMetaData getColVal = (ResultSetMetaData) getValues.getMetaData();
            q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) subTbl.getModel();
            
            
            secAssign.setRowCount(0);
            while (getValues.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = getValues.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
        
            
        } catch (SQLException ex) {
            Logger.getLogger(tablestudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     
     public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    /**
     * @param args the command line arguments
     */
     
     public static void launch(String TCname) {
        TCHLANDING tl = new TCHLANDING(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablesubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablesubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablesubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablesubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveBtn;
    public javax.swing.JLabel adminName;
    public javax.swing.JLabel adminTitle1;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTable subTbl;
    private javax.swing.JComboBox<String> tblFilter;
    // End of variables declaration//GEN-END:variables
}
