/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.teacher;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lordz
 */
public class TCHADVISORY extends javax.swing.JFrame {

    /**
     * Creates new form TCHADVISORY
     */
    public TCHADVISORY(String val,String val2, String val3) {
        initComponents();
        
        tcLabel.setText(val);
        strandVal.setText(val2);
        sec.setText(val3);
        
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        getAdvisory();
        
    }

    Connection conn;
    DefaultComboBoxModel<String> subjectVal = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<String> sectionVal = new DefaultComboBoxModel<>();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        adminTitle = new javax.swing.JLabel();
        tcLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        finalTbl = new javax.swing.JTable();
        subVal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        strandVal = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SEC = new javax.swing.JComboBox<>();
        sec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        adminTitle.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        adminTitle.setText("Welcome,");

        tcLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        tcLabel.setText("TeacherName");

        subTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "LRN", "Name", "IG", "TG"
            }
        ));
        jScrollPane1.setViewportView(subTable);
        if (subTable.getColumnModel().getColumnCount() > 0) {
            subTable.getColumnModel().getColumn(2).setPreferredWidth(12);
            subTable.getColumnModel().getColumn(3).setPreferredWidth(8);
        }

        finalTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "LRN", "Name", "IG", "TG", "Academic Excellence"
            }
        ));
        jScrollPane2.setViewportView(finalTbl);
        if (finalTbl.getColumnModel().getColumnCount() > 0) {
            finalTbl.getColumnModel().getColumn(2).setPreferredWidth(12);
            finalTbl.getColumnModel().getColumn(3).setPreferredWidth(8);
        }

        subVal.setModel(subjectVal);

        jLabel4.setText("FINAL GRADE");

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        strandVal.setText("SN");

        jButton2.setText("Get General Average");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SEC.setModel(sectionVal);
        SEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SECActionPerformed(evt);
            }
        });

        sec.setText("SN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SEC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(subVal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(37, 37, 37))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(adminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tcLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(strandVal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(165, 586, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(448, 448, 448))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(strandVal)
                            .addComponent(sec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SEC)
                            .addComponent(subVal, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButton2)
                        .addGap(170, 170, 170))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getInitialTransmuted();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getStudents();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         TCHSUMMARY tl = new TCHSUMMARY(tcLabel.getText());
        
        tl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void SECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SECActionPerformed
        getSubject();
    }//GEN-LAST:event_SECActionPerformed

    public void getAdvisory(){
        try {
            String tcName = tcLabel.getText();
            PreparedStatement getAdv = conn.prepareStatement("SELECT Class_Name FROM classlist WHERE Adviser_Name = ?");
            getAdv.setString(1,tcName);
                ResultSet findAdv = getAdv.executeQuery();
                    while(findAdv.next()){
                       String sectionName = findAdv.getString("Class_Name");
                            sectionVal.addElement(sectionName);
                    }
        } catch (SQLException ex) {
            Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
   public void getInitialTransmuted(){
        try {
            
            String section = (String) SEC.getSelectedItem();
            String strand = strandVal.getText();
            String subject = (String) subVal.getSelectedItem();
            
            PreparedStatement getGrades = conn.prepareStatement("SELECT * FROM cardGrades WHERE SecVal = ? AND SubVal = ?");
            getGrades.setString(1, section);
            getGrades.setString(2,subject);
                ResultSet findGrades = getGrades.executeQuery();
                
                 DefaultTableModel AssignScore = (DefaultTableModel) subTable.getModel();
        AssignScore.setRowCount(0);
                
                    while(findGrades.next()){
                        String LRN = findGrades.getString("LRN");
                        String NAME = findGrades.getString("NAME");
                        double iGrade = findGrades.getDouble("initialGrade");
                        double tGrade = findGrades.getDouble("transmutedGrade");
                        
                            Object row[] = new Object[subTable.getColumnCount()];
                                row[0] = LRN;
                                row[1] = NAME;
                                row[2] = iGrade;
                                row[3] = tGrade;
                                    
                                AssignScore.addRow(row);
                    }
        } catch (SQLException ex) {
            Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    
    public void getStudents() {
    String sec = (String) SEC.getSelectedItem();
   

    try {
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM cardGrades WHERE SecVal = ? "
        );

        getAssessment.setString(1, sec);
        

        ResultSet getStud = getAssessment.executeQuery();

        // Clear the table model before adding new data
        DefaultTableModel AssignScore = (DefaultTableModel) finalTbl.getModel();
        AssignScore.setRowCount(0);

        // Use a set to track LRNs that have been added
        Set<String> addedLRNs = new HashSet<>();

        while (getStud.next()) {
            String studentLRN = getStud.getString("LRN");
            String studentName = getStud.getString("Name");

            // Check if the student is already added
            if (!addedLRNs.contains(studentLRN)) {
                // Create a new row and populate student details
                Object[] row = new Object[AssignScore.getColumnCount()];
                row[0] = studentLRN;  // Set student LRN
                row[1] = studentName; // Set student name

                // Add the row to the table model
                AssignScore.addRow(row);

                // Mark the LRN as added
                addedLRNs.add(studentLRN);
            }
        }
            getCardGrades();
    } catch (SQLException ex) {
        Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
    }
}
   
   
   public void getCardGrades() {
       try {
           String section = (String)SEC.getSelectedItem();
           String strand = strandVal.getText();
           String TblName = strand +"subjects";
           PreparedStatement getTotalSubs = conn.prepareStatement("SELECT COUNT(SubjectName) FROM "+TblName+" WHERE SecAssigned = ?");
                getTotalSubs.setString(1,section);
                    ResultSet findTS = getTotalSubs.executeQuery();
                        if(findTS.next()){
                          int total = findTS.getInt(1);
                                System.out.println("TOTAL NUMBER OF SUBJECTS: "+total);
                            try {
               String sec = (String) SEC.getSelectedItem();
               String sub = (String) subVal.getSelectedItem();
               
               // Query to get all grades for the specified section and subject
               PreparedStatement getStudent = conn.prepareStatement("SELECT LRN, initialGrade FROM cardGrades WHERE SecVal = ?");
               getStudent.setString(1, sec);
               
               
               ResultSet getVal = getStudent.executeQuery();
               Map<String, Double> initialGrade = new LinkedHashMap<>();
               int count = 0;
               
               // Iterate through the result set
               while (getVal.next()) {
                   String studLRN = getVal.getString("LRN");
                   double percentVal = getVal.getDouble("initialGrade");
                   
                   // Sum the percentages for the same LRN
                   initialGrade.put(studLRN, initialGrade.getOrDefault(studLRN, 0.0) + percentVal/total);
                   count++;
               }
               
               System.out.println("Number of records: " + count);
               Map<String, Map<Double,Double>> finalGrades = new LinkedHashMap<>();
               double transmutedGrade = 0.0;
               String academicEx;
               // Print the results
               for (Map.Entry<String, Double> entry : initialGrade.entrySet()) {
                   String studentLRN = entry.getKey();
                   double iniGrade = entry.getValue();
                   System.out.println("LRN: " + studentLRN + " TOTAL GRADE: " + iniGrade);
                   System.out.println("");
                   
                   if (iniGrade > 99.99) {
                       transmutedGrade = 100;
                   } else if (iniGrade > 98.39) {
                       transmutedGrade =99;
                   } else if (iniGrade > 96.79) {
                       transmutedGrade =98;
                   } else if (iniGrade > 95.19) {
                       transmutedGrade =97;
                   } else if (iniGrade > 93.59) {
                       transmutedGrade =96;
                   } else if (iniGrade > 91.99) {
                       transmutedGrade =95;
                   } else if (iniGrade > 90.39) {
                       transmutedGrade =94;
                   } else if (iniGrade > 88.79) {
                       transmutedGrade =93;
                   } else if (iniGrade > 87.19) {
                       transmutedGrade =92;
                   } else if (iniGrade > 85.59) {
                       transmutedGrade =91;
                   } else if (iniGrade > 83.99) {
                       transmutedGrade =90;
                   } else if (iniGrade > 82.39) {
                       transmutedGrade =89;
                   } else if (iniGrade > 80.79) {
                       transmutedGrade =88;
                   } else if (iniGrade > 79.19) {
                       transmutedGrade =87;
                   } else if (iniGrade > 77.59) {
                       transmutedGrade =86;
                   } else if (iniGrade > 75.99) {
                       transmutedGrade =85;
                   } else if (iniGrade > 74.39) {
                       transmutedGrade =84;
                   } else if (iniGrade > 72.79) {
                       transmutedGrade =83;
                   } else if (iniGrade > 71.19) {
                       transmutedGrade =82;
                   } else if (iniGrade > 69.59) {
                       transmutedGrade =81;
                   } else if (iniGrade > 67.99) {
                       transmutedGrade =80;
                   } else if (iniGrade > 66.39) {
                       transmutedGrade =79;
                   } else if (iniGrade > 64.79) {
                       transmutedGrade =78;
                   } else if (iniGrade > 63.19) {
                       transmutedGrade =77;
                   } else if (iniGrade > 61.59) {
                       transmutedGrade =76;
                   } else if (iniGrade > 59.99) {
                       transmutedGrade =75;
                   } else if (iniGrade > 55.99) {
                       transmutedGrade =74;
                   } else if (iniGrade > 51.99) {
                       transmutedGrade =73;
                   } else if (iniGrade > 47.99) {
                       transmutedGrade =72;
                   } else if (iniGrade > 43.99) {
                       transmutedGrade =71;
                   } else if (iniGrade > 39.99) {
                       transmutedGrade =70;
                   } else if (iniGrade > 35.99) {
                       transmutedGrade =69;
                   } else if (iniGrade > 31.99) {
                       transmutedGrade =68;
                   } else if (iniGrade > 27.99) {
                       transmutedGrade =67;
                   } else if (iniGrade > 23.99) {
                       transmutedGrade =66;
                   } else if (iniGrade > 19.99) {
                       transmutedGrade =65;
                   } else if (iniGrade > 15.99) {
                       transmutedGrade =64;
                   } else if (iniGrade > 11.99) {
                       transmutedGrade =63;
                   } else if (iniGrade > 7.99) {
                       transmutedGrade =62;
                   } else if (iniGrade > 3.99) {
                       transmutedGrade =61;
                   } else if (iniGrade >= 0) {
                       transmutedGrade =60;
                   } else {
                       transmutedGrade = 0; // Handle negative values if needed
                   }
                   Map<String,Double> getTransmuted = new LinkedHashMap<>();
                    getTransmuted.put(studentLRN, transmutedGrade);
                   
                   
                   System.out.println("LRN: "+studentLRN+" INITIAL GRADE: "+iniGrade+" TRANSMUTED GRADE: "+transmutedGrade );
                   Map<Double,Double> getGrades = new LinkedHashMap<>();
                   getGrades.put(iniGrade, transmutedGrade);
                   finalGrades.put(studentLRN, getGrades);
                   
                   // Initialize AEX outside the loop to store all students' academic excellence
Map<String, String> AEX = new LinkedHashMap<>();

// Loop through each student and their transmuted grade
for (Map.Entry<String, Double> transmuted : getTransmuted.entrySet()) {
    String studLRN = transmuted.getKey();
    double transGrade = transmuted.getValue();

    // Determine academic excellence based on the grade
 
    if (transGrade >= 98) {
        academicEx = "With Highest Honor";
    } else if (transGrade >= 95) {
        academicEx = "With High Honor";
    } else if (transGrade >= 90) {
        academicEx = "With Honor";
    } else if (transGrade >= 75) {
        academicEx = "Passed";
    } else if (transGrade >= 60) {
        academicEx = "Failed";
    } else {
        academicEx = "INVALID GRADE";
    }

    // Add the result to the AEX map
    AEX.put(studLRN, academicEx);
}

// Loop through the table and update the academic excellence column
for (int row = 0; row < finalTbl.getRowCount(); row++) {
    // Get the LRN from the first column of the table
    String LRN = (String) finalTbl.getValueAt(row, 0);

    // Check if the LRN exists in the AEX map
    if (AEX.containsKey(LRN)) {
        String acadEx = AEX.get(LRN); // Get the academic excellence value
        finalTbl.setValueAt(acadEx, row, 4); // Update the fifth column (index 4)
    }
}

                            }
               for (int row = 0; row < finalTbl.getRowCount(); row++) {
                   String LRN = (String) finalTbl.getValueAt(row, 0); // Get the LRN from the first column
                   if (finalGrades.containsKey(LRN)) {
                       Map<Double, Double> fGrades = finalGrades.get(LRN);
                      
                       Map.Entry<Double, Double> firstGrade = fGrades.entrySet().iterator().next();
                       finalTbl.setValueAt(firstGrade.getKey(), row, 2); // Set Rating in third column
                       finalTbl.setValueAt(firstGrade.getValue(), row, 3); // Set Percentage in fourth column
                   }
               }
               
               
               
               
           }
           
                            catch (SQLException ex) {
                                Logger.getLogger(SECTIONSOG.class.getName()).log(Level.SEVERE, null, ex);
                            }
            }
       
       }catch (SQLException ex) {
        Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
    }

   
   
}
   
   

   
   
    public void getSubject(){
        String section = (String) SEC.getSelectedItem();
        String strand = strandVal.getText();
            PreparedStatement getSub;
            subjectVal.removeAllElements();
            
            if(strand.equals("ICT")){
            try {
                getSub = conn.prepareStatement("SELECT SubjectName FROM ictsubjects WHERE SecAssigned = ?");
                getSub.setString(1,section);
                    ResultSet findSubs = getSub.executeQuery();
                        while(findSubs.next()){
                            String subs = findSubs.getString("SubjectName");
                            subjectVal.addElement(subs);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(strand.equals("HE")){
            try {
                getSub = conn.prepareStatement("SELECT SubjectName FROM hesubjects WHERE SecAssigned = ?");
                getSub.setString(1,section);
                    ResultSet findSubs = getSub.executeQuery();
                        while(findSubs.next()){
                            String subs = findSubs.getString("SubjectName");
                            subjectVal.addElement(subs);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
            }    
            }else if(strand.equals("GAS")){
                try {
                getSub = conn.prepareStatement("SELECT SubjectName FROM gassubjects WHERE SecAssigned = ?");
                getSub.setString(1,section);
                    ResultSet findSubs = getSub.executeQuery();
                        while(findSubs.next()){
                            String subs = findSubs.getString("SubjectName");
                            subjectVal.addElement(subs);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(strand.equals("ABM")){
                try {
                getSub = conn.prepareStatement("SELECT SubjectName FROM abmsubjects WHERE SecAssigned = ?");
                getSub.setString(1,section);
                    ResultSet findSubs = getSub.executeQuery();
                        while(findSubs.next()){
                            String subs = findSubs.getString("SubjectName");
                            subjectVal.addElement(subs);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(TCHADVISORY.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                System.out.println("There is no strand like this exists.");
            }
            
    }
    
    
  
    
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    
     public static void launch(String tchVal, String strandVal,String sectionVal) {
        TCHADVISORY tl = new TCHADVISORY(tchVal,strandVal,sectionVal);
         // Set the sub value if needed
        tl.setVisible(true);
    }
     
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHADVISORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHADVISORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHADVISORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHADVISORY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("","","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SEC;
    public javax.swing.JLabel adminTitle;
    private javax.swing.JTable finalTbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel sec;
    private javax.swing.JLabel strandVal;
    private javax.swing.JTable subTable;
    private javax.swing.JComboBox<String> subVal;
    public javax.swing.JLabel tcLabel;
    // End of variables declaration//GEN-END:variables
}
