/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.teacher;

import com.evaluenet.login.LoginUI;
import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aicel
 */
public class TCHLANDING extends javax.swing.JFrame {

    /**
     * Creates new form TCHLANDING
     */
    public TCHLANDING(String tchVal) {
        initComponents();
            tcName.setText(tchVal);
        
        
        try {
            
            
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(TCHLANDING.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TCHLANDING.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        cardTmplt.setEnabled(false);
        sf10.setEnabled(false);
    
        
    }

    Connection conn;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sf10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cardTmplt = new javax.swing.JButton();
        randText = new javax.swing.JLabel();
        tcName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        sf10.setBackground(new java.awt.Color(204, 255, 204));
        sf10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        sf10.setText("SF10");
        sf10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sf10ActionPerformed(evt);
            }
        });
        getContentPane().add(sf10);
        sf10.setBounds(390, 500, 530, 70);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setText("LOG OUT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1100, 30, 110, 40);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton3.setText("GRADING SHEET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 170, 530, 70);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setText("SUMMARY OF GRADES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(390, 280, 530, 70);

        cardTmplt.setBackground(new java.awt.Color(204, 255, 204));
        cardTmplt.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        cardTmplt.setText("CARD TEMPLATE");
        cardTmplt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardTmpltActionPerformed(evt);
            }
        });
        getContentPane().add(cardTmplt);
        cardTmplt.setBounds(390, 390, 530, 70);

        randText.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        randText.setText("Welcome,");
        getContentPane().add(randText);
        randText.setBounds(160, 40, 100, 20);

        tcName.setFont(new java.awt.Font("Tw Cen MT", 1, 20)); // NOI18N
        tcName.setText("TeacherName");
        getContentPane().add(tcName);
        tcName.setBounds(250, 40, 240, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/evaluenet/teacher/2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1330, 760);

        setSize(new java.awt.Dimension(1294, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sf10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sf10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sf10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LoginUI l1 = new LoginUI();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
        dispose();
        l1.setVisible(true);
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String tchVal = tcName.getText();
        
        TCHSECTION ts = new TCHSECTION(tchVal);
        ts.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String tchVal = tcName.getText();
        
        TCHSUMMARY ts = new TCHSUMMARY(tchVal);
        ts.setVisible(true);
        this.setVisible(false);
        ts.tcLabel.setText(tcName.getText());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cardTmpltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardTmpltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardTmpltActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_formWindowActivated

    public void getFN(){
        
        
        this.revalidate();
        this.repaint();
    }     
    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void launch(String TCname) {
        TCHLANDING tl = new TCHLANDING(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCHLANDING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCHLANDING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCHLANDING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCHLANDING.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cardTmplt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel randText;
    private javax.swing.JButton sf10;
    public javax.swing.JLabel tcName;
    // End of variables declaration//GEN-END:variables
}
