/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.assessmentlist;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author lordz
 */
public class QuizList extends javax.swing.JFrame {

    /**
     * Creates new form QuizList
     */
    public QuizList(String sec, String sub) {
        initComponents();
        secName.setText(sec);
        subName.setText(sub);
        
        System.out.println("The SECTION IS??!?!? "+ secName.getText());
        try {
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        quizTbl.setDefaultEditor(Object.class, null);
    }

    
    Connection conn;
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        secName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        quizTbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        CBforQN = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));

        subName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subName.setText("Subject");

        jLabel2.setText("QUIZ LIST");

        secName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        secName.setText("Section");

        quizTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "LRN", "Quiz Scores"
            }
        ));
        jScrollPane1.setViewportView(quizTbl);

        jButton1.setText("get Scores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CBforQN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        jLabel3.setText("Quiz No.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBforQN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel3)
                    .addComponent(secName, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(subName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(596, 596, 596)
                    .addComponent(jLabel2)
                    .addContainerGap(633, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(secName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(CBforQN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(jLabel2)
                    .addContainerGap(710, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getScores();
    }//GEN-LAST:event_jButton1ActionPerformed

     
    
   
    
  public void getScores() {
    try {
            String secVal = secName.getText();
    String subVal = subName.getText();
        String quiz = "Quiz";
        String quizNumber = (String) CBforQN.getSelectedItem();
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ? AND assessmentNum = ?"
        );

        getAssessment.setString(1, secVal);
        getAssessment.setString(2, subVal);
        getAssessment.setString(3, quiz);
        getAssessment.setString(4, quizNumber);
        

        ResultSet getQuiz = getAssessment.executeQuery();

        // Clear the table model once, before processing any quizzes
        DefaultTableModel AssignScore = (DefaultTableModel) quizTbl.getModel();
        AssignScore.setRowCount(0);
        int columnIndex = 2; // Assuming first two columns are for student name and LRN

        if(getQuiz.next()) {
            String AID = getQuiz.getString("assessment_id");
            String QN = getQuiz.getString("assessmentNum");
            
           
            PreparedStatement scores = conn.prepareStatement(
                "SELECT studNAME, studLRN, score, assessmentID FROM tblscores WHERE assessmentID = ?"
            );
            scores.setString(1, AID);
            ResultSet scoreVal = scores.executeQuery();
            
            while (scoreVal.next()) {
                String studentLRN = scoreVal.getString("studLRN");
                String studentName = scoreVal.getString("studNAME");
                Object score = scoreVal.getObject("score");
                    
                
                    // If the student is not in the map, create a new row and add student details
                    Object[] row = new Object[AssignScore.getColumnCount()];
                    row[0] = studentName; // Set student name
                    row[1] = studentLRN;  // Set student LRN
                    row[2] = score; // Set score for the current quiz

                    // Store this row in the map
                    
                    AssignScore.addRow(row); // Add the new row to the table model
                    
                    
            }
                    
        }
        
    } catch (SQLException ex) {
        Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
    }
}

   public void getFinalGrades() {
    try {
            String secVal = secName.getText();
    String subVal = subName.getText();
        DefaultTableModel AssignRP = (DefaultTableModel) quizTbl.getModel();
        double totalItems = 0;
        int percentage = 20;
        String quiz = "Quiz";
        
        PreparedStatement getAssessment = conn.prepareStatement(
            "SELECT * FROM tblassessment WHERE className = ? AND subjectName = ? AND assessmentType = ?"
        );

        getAssessment.setString(1, secVal);
        getAssessment.setString(2, subVal);
        getAssessment.setString(3, quiz);

        ResultSet getQuiz = getAssessment.executeQuery();

        // Collect all quizzes
        Map<String, String> quizMap = new LinkedHashMap<>(); // QuizNum -> AssessmentID
        while (getQuiz.next()) {
            String assessmentID = getQuiz.getString("assessment_id");
            String quizNum = getQuiz.getString("assessmentNum");
            int totalItm = getQuiz.getInt("totalItems");
            totalItems += totalItm;
            quizMap.put(quizNum, assessmentID);
        }
        
        System.out.println("Section: " + secVal + " Subject: " + subVal + " Total Score: " + totalItems);

        // Collect all student scores
        Map<String, Map<String, Integer>> studentScores = new LinkedHashMap<>(); // LRN -> {QuizNum -> Score}
        Map<String, Integer> totalScores = new LinkedHashMap<>(); // LRN -> Total Score

        for (Map.Entry<String, String> entry : quizMap.entrySet()) {
            String quizNum = entry.getKey();
            String assessmentID = entry.getValue();

            PreparedStatement scores = conn.prepareStatement(
                "SELECT studNAME, studLRN, score FROM tblscores WHERE assessmentID = ?"
            );
            scores.setString(1, assessmentID);
            ResultSet scoreVal = scores.executeQuery();

            while (scoreVal.next()) {
                String studentLRN = scoreVal.getString("studLRN");
                int score = scoreVal.getInt("score");

                // Add or update the student's scores
                studentScores.putIfAbsent(studentLRN, new LinkedHashMap<>());
                studentScores.get(studentLRN).put(quizNum, score);
                
                // Update the total score for the student
                totalScores.putIfAbsent(studentLRN, 0); // Initialize total score if not present
                totalScores.put(studentLRN, totalScores.get(studentLRN) + score); // Add the current score to total
            }
        }

        // Prepare final grades
        Map<String, Map<Double, Double>> finalGrades = new LinkedHashMap<>(); // LRN -> {Rating -> Percentage}
        StringBuilder output = new StringBuilder("Final Grades:\n\n");

        for (Map.Entry<String, Map<String, Integer>> studentEntry : studentScores.entrySet()) {
            String studentLRN = studentEntry.getKey();
            double totalScore = totalScores.get(studentLRN);
            double ratingVal = (totalScore / totalItems) * 100;
            double percentVal = ratingVal * percentage / 100;

            output.append("Student LRN: ").append(studentLRN).append("\n");
            output.append("  Total Score: ").append(totalScore).append("\n");
            output.append("  Rating: ").append(ratingVal).append("\n");
            output.append("  Percentage: ").append(percentVal).append("\n\n");

            System.out.println("Student: " + studentLRN + " Rating: " + ratingVal + " Percentage: " + percentVal);

            Map<Double, Double> grades = new LinkedHashMap<>();
            grades.put(ratingVal, percentVal);
            finalGrades.put(studentLRN, grades);
        }

        // Update the table
        for (int row = 0; row < AssignRP.getRowCount(); row++) {
            String LRN = (String) AssignRP.getValueAt(row, 1); // Get the LRN from the first column
            if (finalGrades.containsKey(LRN)) {
                Map<Double, Double> fGrades = finalGrades.get(LRN);
                Map.Entry<Double, Double> firstGrade = fGrades.entrySet().iterator().next();
                AssignRP.setValueAt(firstGrade.getKey(), row, 3); // Set Rating in third column
                AssignRP.setValueAt(firstGrade.getValue(), row, 4); // Set Percentage in fourth column
            }
        }



        // Optionally, output to the console
        System.out.println(output);

    } catch (SQLException ex) {
        Logger.getLogger(QuizList.class.getName()).log(Level.SEVERE, null, ex);
    }
}

   


    
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }


    
    
    
    
    
    
public static void launch(String secVal, String subVal) {
        QuizList tlp = new QuizList(secVal, subVal);
         // Set the sub value if needed
        tlp.setVisible(true);
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("","");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBforQN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable quizTbl;
    public javax.swing.JLabel secName;
    public javax.swing.JLabel subName;
    // End of variables declaration//GEN-END:variables
}
