/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.login.page;

//Essential import classes
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.Timer;
/**
 *
 * @author PC
 */
public class login extends javax.swing.JFrame {

    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        disableCopy(userLP);
        disableCopy(passLP);
        disablePaste(userLP);
        disablePaste(passLP);        
            try {
                establishConnection(); //function calling
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void disableCopy(JComponent component){
        component.getInputMap().put(KeyStroke.getKeyStroke("control C"), "none");
    }
    
    private void disablePaste(JComponent component){
        component.getInputMap().put(KeyStroke.getKeyStroke("control V"), "none");
    }
    
    private void disableCP(JComponent component){
        disableCopy(component);
        disablePaste(component);
    }
    
    
//Variable initialization
    Connection conn;
    int i = 4;
    String format = ".*[A-Z].*";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userLP = new javax.swing.JTextField();
        passLP = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(629, 397));
        getContentPane().setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/login/page/Untitled design (2).png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, -30, 260, 450);

        jPanel2.setBackground(new java.awt.Color(26, 68, 45));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EvaluNet (Grading System V.1)");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 370, 250, 27);

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(476, 406, 170, 0);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/login/page/259.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 90, 250, 250);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("C.O.D.E.S");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 104, 27);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 300, 400);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 120, 100, 16);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 68, 45));
        jLabel4.setText("Forgot Password?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 230, 110, 16);

        userLP.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        userLP.setToolTipText("");
        userLP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLPActionPerformed(evt);
            }
        });
        getContentPane().add(userLP);
        userLP.setBounds(370, 140, 180, 30);
        getContentPane().add(passLP);
        passLP.setBounds(370, 200, 180, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 180, 110, 16);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 34)); // NOI18N
        jLabel14.setText("SIGN IN");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 67, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/login/page/3.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 270, 250, 290);

        jButton2.setBackground(new java.awt.Color(26, 68, 45));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(420, 260, 100, 28);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/login/page/3.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 270, 250, 290);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/login/page/3.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(330, 270, 250, 290);

        jPanel4.setBackground(new java.awt.Color(242, 239, 238));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(300, 0, 300, 400);

        setSize(new java.awt.Dimension(617, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userLPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLPActionPerformed

//Login button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     if(userLP.getText().equals("")){ //Checks if username textfield is blank
         JOptionPane.showMessageDialog(null,"Please enter your username.");
     }else if(passLP.getText().equals("")){ //Checks if password textfield is blank
         JOptionPane.showMessageDialog(null,"Please enter your password.");
     }else{
             String user = userLP.getText().trim();
             String pass = passLP.getText().trim();
             String sqlQuery = "SELECT*FROM tblaccounts WHERE username = ? AND password = ?"; //Looks for the UN and PW value
             
        try {
            //Checking credentials
                PreparedStatement pstmt = conn.prepareStatement(sqlQuery);
                pstmt.setString(1, user); //Sets String user to column, username
                pstmt.setString(2, pass); //Sets String pass to column, password
                ResultSet verify = pstmt.executeQuery();
            //Checking attempts    
                String limitcnt = "SELECT logAttempt FROM tblaccounts WHERE username = ?";   
             PreparedStatement limitCheck = conn.prepareStatement(limitcnt);
             limitCheck.setString(1, user);
                ResultSet checkLimit = limitCheck.executeQuery();
              
              
            if(verify.next() && user.matches(format)){ //Verifies username & password                
                if(checkLimit.next()){
                    int limitVal = checkLimit.getInt("logAttempt");
                        if(limitVal < 4){  
                            //Level of access
                if(user.contains("STUD")){
                    dispose();
                    student s1 = new student();
                    s1.setVisible(true);
                }else if(user.contains("ADMIN")){
                    dispose();
                    admin a1 = new admin();
                    a1.setVisible(true);
                }else if(user.contains("TCH")){
                    dispose();
                    teacher t1 = new teacher();
                    t1.setVisible(true);
                }else if(user.contains("IT")){
                    dispose();
                    it i1 = new it();
                    i1.setVisible(true);
                }else if(user.contains("HR")){
                    dispose();
                   hr h1 = new hr();
                    h1.setVisible(true);
                    }
                }else if(limitVal == 4){
                    JOptionPane.showMessageDialog(null, "Login limit has been reached. Account locked.");
                        int ans = JOptionPane.showConfirmDialog(null, "Do you want to try another account?", "Yes/No Dialog", JOptionPane.YES_NO_OPTION);
                            if(ans == JOptionPane.YES_OPTION) {
                                userLP.setText(""); //Clears username Textfield 
                                passLP.setText("");  
                            }else if(ans == JOptionPane.NO_OPTION) {
                                dispose();  
                            }
                      }
                }
            }else{               
                if(checkLimit.next() && user.matches(format) ){
                    int limitValue = checkLimit.getInt("logAttempt");   
                    String limit = "UPDATE tblaccounts SET logAttempt = logAttempt + 1 WHERE username = ?";
                PreparedStatement lmtcheckupdate = conn.prepareStatement(limit);
                    lmtcheckupdate.setString(1,user);
                
                if(limitValue != i){ //defines the limits of access
                    int increment = lmtcheckupdate.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Incorrect username or password");
                        userLP.setText(""); //Clears username Textfield 
                        passLP.setText(""); //Clears password Textfield    
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Login limit has been reached. Account locked.");
                    int ans = JOptionPane.showConfirmDialog(null, "Do you want to try another account?", "Yes/No Dialog", JOptionPane.YES_NO_OPTION);
                        if(ans == JOptionPane.YES_OPTION) {
                          userLP.setText(""); //Clears username Textfield 
                          passLP.setText("");  
                        } else if(ans == JOptionPane.NO_OPTION) {
                          dispose();  
                        }
                }
            }else{
                JOptionPane.showMessageDialog(null,"Account not found.");
                    userLP.setText(""); //Clears username Textfield 
                    passLP.setText(""); //Clears password Textfield 
                }
         } 
        } catch (SQLException ex) {
             Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex); 
         }
    }//GEN-LAST:event_jButton2ActionPerformed
    }
//Directs user to Forgot Password Page
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
            forgot fgotPage = new forgot();
                fgotPage.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

//Connecting Java to SQL server
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField passLP;
    private javax.swing.JTextField userLP;
    // End of variables declaration//GEN-END:variables
}
