/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.it;

import com.evaluenet.login.login;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC
 */
public class forgot extends javax.swing.JFrame {

    /**
     * Creates new form forgot
     */
    public forgot() {
        initComponents();
        try {   
            establishConnection();
        } catch (SQLException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Connection conn;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ansSQ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chosenSQ = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 800));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, -30, 260, 0);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setText("Answer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 410, 100, 16);

        jButton2.setBackground(new java.awt.Color(26, 68, 45));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 500, 120, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel14.setText("Security Question");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 170, 310, 47);

        ansSQ.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        ansSQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansSQActionPerformed(evt);
            }
        });
        getContentPane().add(ansSQ);
        ansSQ.setBounds(520, 440, 260, 40);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel4.setText("Security Question");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 320, 210, 20);

        chosenSQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a question", "What's the name of your first pet?", "What is your favorite food?", "Who is your favorite person?" }));
        chosenSQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chosenSQActionPerformed(evt);
            }
        });
        getContentPane().add(chosenSQ);
        chosenSQ.setBounds(520, 360, 260, 40);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel15.setText("Username");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(480, 230, 120, 32);
        getContentPane().add(userField);
        userField.setBounds(520, 270, 260, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EvalueNetPackage/2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1280, 800);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        saveSQ();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ansSQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansSQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansSQActionPerformed

    private void chosenSQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosenSQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chosenSQActionPerformed

    
    
    public void saveSQ(){
        try {
            String User = userField.getText();
            PreparedStatement getUN = conn.prepareStatement("SELECT username,SEC_QUES FROM tblaccounts WHERE username = ?");
            getUN.setString(1, User);
            ResultSet findUN = getUN.executeQuery();
            
        if(findUN.next()){
            
            String UN = findUN.getString("username");
            String SQVal = findUN.getString("SEC_QUES");
            
            if(!SQVal.equals("none")){
            
            int sqVal = chosenSQ.getSelectedIndex();
            String ansVal = ansSQ.getText();
            
            if(UN.equals("")){
                JOptionPane.showMessageDialog(null,"Please enter your username.");
            }else if(sqVal == 0){
                JOptionPane.showMessageDialog(null,"Please selecct a security question");
            }else if(ansVal.equals("")){
                JOptionPane.showMessageDialog(null,"Please enter your answer");
            }else{
                try {
                    PreparedStatement findUser = conn.prepareStatement("SELECT username,SEC_QUES FROM tblaccounts WHERE username = ?");
                    findUser.setString(1,UN);
                    ResultSet userName = findUser.executeQuery();
                    if(userName.next()){
                        String unVal = userName.getString("username");
                       
                        
                        
                        String CSQ =(String) chosenSQ.getSelectedItem();
                        PreparedStatement insVal = conn.prepareStatement("UPDATE tblaccounts SET SEC_QUES = ?, ANS_SQ = ? WHERE username = ?");
                        insVal.setString(1,CSQ);
                        insVal.setString(2,ansVal);
                        insVal.setString(3,unVal);
                        insVal.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Security Question set successfully");
                        login log = new login();
                        log.setVisible(true);
                        this.setVisible(false);
                        
                        
                        }else{
                        JOptionPane.showMessageDialog(null,"Username is invalid");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this,"Error inserting value: "+ex.getMessage());
                }
                
            }
}
        
        }else{
            JOptionPane.showMessageDialog(null, "Username not found.");
        }
            
        }
        
        catch (SQLException ex) {
            Logger.getLogger(forgot.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
    }
    
    //Connecting Java to SQL server
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansSQ;
    private javax.swing.JComboBox<String> chosenSQ;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
