/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.evaluenet.it;

import com.evaluenet.admin.tablesf1;
import com.evaluenet.login.login;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
/**
 *
 * @author aicel
 */
public class ITADDACC extends javax.swing.JFrame {

    /**
     * Creates new form ITADDACC
     */
    public ITADDACC(String val) {
        initComponents();
        itVal.setText(val);
        try {
            establishConnection();
        } catch (SQLException ex) {
            System.getLogger(ITADDACC.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(ITADDACC.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        getItem();
    }
    
    
    //-------------------------
    // VARIABLE INITIALIZATION
    //-------------------------
    Connection conn;
    
    
    //-----------------------
    // ESTABLISHING DATABASE
    //-----------------------
    public void establishConnection() throws SQLException, ClassNotFoundException{
        
            Class.forName("com.mysql.cj.jdbc.Driver"); //Driver Connection
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/evaluenet","root","gRadingsystemDB2024"); //Database Connection
        //Checks connection
            if(conn != null){
                System.out.println("Connection successfully");
            }
    }
    
    //-----------------
    //TABLE FUNCTION/S
    //-----------------
    public void getItem(){
         
             try {    
                 PreparedStatement getSec = conn.prepareStatement("SELECT FullName, username, userType FROM tblaccounts ");
                    
                    ResultSet findSection = getSec.executeQuery();
                         ResultSetMetaData getColVal = (ResultSetMetaData) findSection.getMetaData();
            int q = getColVal.getColumnCount();
            DefaultTableModel secAssign = (DefaultTableModel) accTable.getModel();
            secAssign.setRowCount(0);
            accTable.setDefaultEditor(Object.class, null);
            while (findSection.next()) {
                Object[] row = new Object[q];
                for (int i = 1; i <= q; i++) {
                    row[i - 1] = findSection.getObject(i); // Get each column value
                }
                secAssign.addRow(row); // Add the row to the table model
            }
             } catch (SQLException ex) {
                 Logger.getLogger(tablesf1.class.getName()).log(Level.SEVERE, null, ex);
             }
         
               
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        manageAccBtn = new javax.swing.JButton();
        resetLimitBtn = new javax.swing.JButton();
        sqBtn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        itVal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 108, 72));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IT Dashboard");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 70);

        jPanel4.setBackground(new java.awt.Color(0, 153, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageAccBtn.setBackground(new java.awt.Color(0, 153, 102));
        manageAccBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        manageAccBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageAccBtn.setText("MANAGE ACCOUNTS");
        manageAccBtn.setBorder(null);
        manageAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAccBtnActionPerformed(evt);
            }
        });
        jPanel4.add(manageAccBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 192, 270, 90));

        resetLimitBtn.setBackground(new java.awt.Color(0, 153, 102));
        resetLimitBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        resetLimitBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetLimitBtn.setText("RESET LIMITS");
        resetLimitBtn.setBorder(null);
        resetLimitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetLimitBtnActionPerformed(evt);
            }
        });
        jPanel4.add(resetLimitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, 270, 87));

        sqBtn.setBackground(new java.awt.Color(0, 153, 102));
        sqBtn.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        sqBtn.setForeground(new java.awt.Color(255, 255, 255));
        sqBtn.setText("ADD SECURITY QUESTION");
        sqBtn.setBorder(null);
        sqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqBtnActionPerformed(evt);
            }
        });
        jPanel4.add(sqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 381, 270, 90));

        jButton11.setBackground(new java.awt.Color(0, 108, 72));
        jButton11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("GO BACK");
        jButton11.setBorder(null);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 250, 56));

        jButton10.setBackground(new java.awt.Color(0, 108, 72));
        jButton10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("LOG OUT");
        jButton10.setBorder(null);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 250, 55));

        itVal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itVal.setForeground(new java.awt.Color(255, 255, 255));
        itVal.setText("Lord Zierwin");
        jPanel4.add(itVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("IT Administrator");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 50));

        jPanel2.setBackground(new java.awt.Color(0, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 2));
        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 290, 120));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 270, 800);

        jPanel3.setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(330, 120, 270, 100);

        jPanel5.setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(330, 240, 220, 430);

        accTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Username", "User Type"
            }
        ));
        jScrollPane1.setViewportView(accTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 240, 650, 430);

        jPanel6.setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel6);
        jPanel6.setBounds(620, 120, 300, 100);

        jPanel7.setBackground(new java.awt.Color(0, 153, 102));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(940, 120, 280, 100);

        setSize(new java.awt.Dimension(1294, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetLimitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetLimitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resetLimitBtnActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
   login l1 = new login();
        int answer = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Logout Confirmation", JOptionPane.YES_NO_OPTION);
            if(answer == JOptionPane.YES_OPTION){
        dispose();
        l1.setVisible(true);
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void sqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqBtnActionPerformed
        forgot f1 = new forgot();
                f1.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_sqBtnActionPerformed

    private void manageAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAccBtnActionPerformed
        ITADDACCFORM iaf = new ITADDACCFORM(itVal.getText());
        this.dispose();
        iaf.setVisible(true);
    }//GEN-LAST:event_manageAccBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void launch(String TCname) {
        ITADDACC tl = new ITADDACC(TCname);
         // Set the sub value if needed
        tl.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITADDACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITADDACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITADDACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITADDACC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                launch("");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accTable;
    private javax.swing.JLabel itVal;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageAccBtn;
    private javax.swing.JButton resetLimitBtn;
    private javax.swing.JButton sqBtn;
    // End of variables declaration//GEN-END:variables
}
